import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider with ChangeNotifier {
  static const String _languageKey = 'app_language_code';

  // Default to English (US)
  String _currentLanguageCode = 'en';
  String _currentLanguageName = 'English (US)';

  final List<Map<String, String>> _supportedLanguages = [
    {'code': 'en', 'name': 'English (US)'},
    {'code': 'sw', 'name': 'Kiswahili'},
    {'code': 'es', 'name': 'Español'},
    {'code': 'fr', 'name': 'Français'},
    {'code': 'de', 'name': 'Deutsch'},
    {'code': 'pt', 'name': 'Português'},
  ];

  LanguageProvider() {
    _loadLanguage();
  }

  String get currentLanguageCode => _currentLanguageCode;
  String get currentLanguageName => _currentLanguageName;
  List<Map<String, String>> get supportedLanguages => _supportedLanguages;

  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final savedCode = prefs.getString(_languageKey);
    if (savedCode != null) {
      _currentLanguageCode = savedCode;
      _currentLanguageName = _supportedLanguages.firstWhere(
        (lang) => lang['code'] == savedCode,
        orElse: () => _supportedLanguages[0],
      )['name']!;
      notifyListeners();
    }
  }

  Future<void> setLanguage(String code) async {
    final lang = _supportedLanguages.firstWhere(
      (l) => l['code'] == code,
      orElse: () => _supportedLanguages[0],
    );

    _currentLanguageCode = lang['code']!;
    _currentLanguageName = lang['name']!;

    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, _currentLanguageCode);

    notifyListeners();
  }

  String getString(String key) {
    if (_translations[_currentLanguageCode]?.containsKey(key) ?? false) {
      return _translations[_currentLanguageCode]![key]!;
    }
    // Fallback to English
    return _translations['en']?[key] ?? key;
  }

  final Map<String, Map<String, String>> _translations = {
    'en': {
      'select_language': 'Select Language',
      'settings_title': 'Settings',
      'account': 'Account',
      'my_meetups': 'My Meet Ups',
      'preferences': 'Preferences',
      'discovery': 'Discovery',
      'video_chat': 'Video chat',
      'support': 'Support',
      'edit_profile': 'Edit Profile',
      'edit_profile_sub': 'Change your profile details',
      'email_settings': 'Email Settings',
      'email_settings_sub': 'Update your email address',
      'security': 'Security',
      'security_sub': 'Password, blocked users',
      'blocked_users': 'Blocked Users',
      'night_mode': 'Night Mode',
      'night_mode_on': 'Dark theme enabled',
      'night_mode_off': 'Light theme enabled',
      'language': 'Language',
      'reset_swipes': 'Reset Swipes',
      'reset_swipes_sub': 'See previously swiped profiles again',
      'help_center': 'Help Center',
      'help_center_sub': 'FAQs and support chat',
      'terms_of_service': 'Terms of Service',
      'terms_of_service_sub': 'Legal information',
      'delete_account': 'Delete Account',
      'delete_account_sub': 'Permanently remove your profile and data',
      'wipe_local_data': 'Wipe Local Data',
      'wipe_local_data_sub': 'Clear offline cache and local database',
      'wipe_confirm_title': 'Wipe Local Data?',
      'wipe_confirm_content':
          'This will clear all locally stored data including Firestore cache, shared preferences, and the local database. You will need to re-sync with the server.\n\nThis action cannot be undone.',
      'wipe_success': 'Local data wiped successfully!',
      'wipe_failed': 'Failed to wipe local data.',
      'signin_title': 'Welcome Back',
      'signin_sub': 'Sign in to continue your journey',
      'email': 'Email Address',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'signin_button': 'Sign In',
      'no_account': 'Don\'t have an account?',
      'signup_link': 'Sign Up',
      'signup_button': 'Sign Up',
      'or_continue_with': 'Or continue with',
      'google_signin': 'Continue with Google',
      'like': 'Like',
      'pass': 'Pass',
      'rewind': 'Rewind',
      'view_profile': 'View Profile',
      'no_profiles_title': 'You\'ve seen everyone!',
      'no_profiles_sub': 'Come back later or refresh to revisit profiles.',
      'refresh_profiles': 'Refresh Profiles',
      'finding_matches': 'Finding your matches…',
      'like_stamp': 'LIKE',
      'nope_stamp': 'NOPE',
      'add_photos_now': 'Add Photos Now',
      'upload_more_photos_title': 'Upload More Photos',
      'upload_more_photos_sub':
          'Add at least 4 photos to your profile to keep swiping, view profiles, and browse photos.',
      'view_full_profile': 'View Full Profile',
      'about_me': 'About Me',
      'quick_facts': 'Quick Facts',
      'background': 'Background',
      'lifestyle': 'Lifestyle',
      'relationship_goals': 'Relationship Goals',
      'interests_hobbies': 'Interests & Hobbies',
      'music_taste': 'Music Taste',
      'personality': 'Personality',
      'prompts': 'Prompts',
      'message': 'Message',
      'height_label': 'Height',
      'education_label': 'Education',
      'religion_label': 'Religion',
      'wants_kids_label': 'Wants Kids',
      'long_distance_label': 'Long Distance',
      'body_type_label': 'Body Type',
      'status_label': 'Status',
      'school_label': 'School',
      'want_kids_label': 'Want Kids?',
      'occupation_label': 'Occupation',
      'industry_label': 'Industry',
      'education_level_label': 'Education Level',
      'introvert_extrovert_label': 'Introvert or Extrovert?',
      'languages_spoken_label': 'Languages',
      'smoking_label': 'Smoking',
      'drinking_label': 'Drinking',
      'exercise_label': 'Mazoezi',
      'diet_label': 'Diet',
      'sleep_label': 'Sleep',
      'pets_label': 'Pets',
      'zodiac_label': 'Zodiac Sign',
      'personality_type_label': 'Personality Type',
      'social_style_label': 'Social Style',
      'love_language_label': 'Love Language',
      'core_values_label': 'Core Values',
      'notifications': 'Notifications',
      'notifications_sub': 'Manage your alerts and sounds',
      'privacy_visibility': 'Privacy & Visibility',
      'show_age': 'Show Age',
      'show_age_sub': 'Display your age on your profile',
      'show_distance': 'Show Distance',
      'show_distance_sub': 'Display how far you are from others.',
      'hide_profile': 'Hide Profile',
      'hide_profile_sub':
          'Temporarily hide your profile from search & discovery',
      'allow_messages_label': 'Allow Messages',
      'allow_messages_sub': 'Receive direct messages from other users.',
      'allow_bookings_label': 'Allow Meetup Requests',
      'allow_bookings_sub': 'Let other users send you date requests.',
      'booking_preferences': 'Meetup Details',
      'booking_details': 'Edit Meetup Details',
      'booking_details_sub': 'Set your location, rate, and rules for dates.',
      'booking_details_hint':
          'These details will be shown to users who want to book a date with you.',
      'booking_location_label': 'Preferred Location',
      'booking_rate_label': 'Requirements',
      'booking_notes_label': 'Rules & Notes',
      'my_bookings': 'My Meetups',
      'reset_swipes_title': 'Reset Swipes',
      'reset_swipes_content':
          'This will clear your "Pass" history. You will see users you passed on again, but your "Likes" will remain.\n\nThis action cannot be undone.',
      'cancel': 'Cancel',
      'reset': 'Reset',
      'swipes_reset_success': 'Swipes reset! Fresh profiles are loading.',
      'swipes_reset_failed': 'Failed to reset swipes. Please try again.',
      'photo_lock_snack': 'Upload at least 4 photos to browse more pictures!',
      'upload_label': 'Upload',
      'messages_disabled_snack': 'This user has disabled direct messaging.',
      'refresh_cost_title': 'Confirm Refresh',
      'refresh_cost_content':
          'Refreshing profiles costs 50 sparks. Your current balance is {credits} sparks.',
      'not_enough_credits':
          'Not enough sparks. Please top up to refresh profiles.',
      'pay_refresh': 'Pay 50 Sparks',
      'send_gift': 'Send Gift',
      'gift_sent_success': 'Gift sent successfully!',
      'select_gift': 'Select a Gift',
      'received_gift_suffix': 'sent you a gift!',
      'signup_title': 'Create Account',
      'signup_sub': 'Join Snellum and find your perfect match',
      'full_name': 'Full Name',
      'already_have_account': 'Already have an account?',
      'register_with': 'Or register with',
      'fill_all_fields': 'Please fill all fields',
      'likes_label': 'Likes',
      'visitors_label': 'Visitors',
      'matches_label': 'Matches',
      'account_section': 'Account',
      'my_profile': 'My Profile',
      'settings_label': 'Settings',
      'discovery_section': 'Discovery',
      'explore_people': 'Explore People',
      'activity_section': 'Activity',
      'blog': 'Blog',
      'live_videos': 'Video Chat',
      'finance_section': 'Finance',
      'go_premium': 'Go Premium',
      'my_credits': 'My Sparks',
      'gifts': 'Gifts',
      'transactions': 'Transactions',
      'appearance_section': 'Appearance',
      'support_section': 'Support',
      'about_us': 'About Us',
      'safety_tips': 'Safety Tips',
      'logout': 'Logout',
      'logout_sub': 'Sign out of your account',
      'light_mode': 'Light Mode',
      'dark_mode': 'Dark Mode',
      'nav_swipe': 'Swipe',
      'nav_explore': 'Explore',
      'nav_likes': 'Likes',
      'nav_chat': 'Chat',
      'profile_needs_attention': 'Profile Needs Attention',
      'profile_completion_sub':
          'Your profile is currently {completion}% complete. You need to complete your profile past 40% before you can start matching, chatting, and exploring!',
      'complete_profile_button': 'Complete Profile',
      'signout_label': 'Sign Out',
      'unread_notifications': 'Notifications',
      'join_community': 'Join the community',
      'signin_to_see_likes': 'Please sign in to see likes',
      'all_likes': 'All Likes',
      'new_likes': 'New Likes',
      'no_likes_yet': 'No likes yet',
      'keep_swiping_matches': 'Keep swiping to find matches!',
      'someone_fallback': 'Someone',
      'visitors_header': 'Recent Viewers',
      'no_visitors_yet': 'No views yet',
      'no_visitors_sub': 'People who visited your profile will appear here.',
      'messages_title': 'Messages',
      'no_messages_yet': 'No messages yet',
      'no_messages_sub': 'Your conversations will appear here.',
      'search_hint': 'Search...',
      'signin_to_view_messages': 'Please sign in to view messages',
      'failed_load_messages': 'Failed to load messages',
      'retry_button': 'Retry',
      'no_conversations_yet': 'No conversations yet',
      'no_conversations_sub': 'Like someone to start a conversation',
      'new_matches_header': 'New Matches',
      'no_matches_yet_sub': 'No matches yet. Keep swiping!',
      'recent_messages_header': 'Recent Messages',
      'say_hello': 'Say hello!',
      'you_prefix': 'You:',
      'user_fallback': 'User',
      'welcome_back': 'Welcome back!',
      'profile_complete_title': 'Profile Complete!',
      'complete_your_profile': 'Complete Your Profile',
      'tap_update_details': 'Tap here to update your details',
      'matches_3x_likely': 'Matches are 3x more likely with a full profile.',
      'views_label': 'Views',
      'edit_profile_label': 'Edit Profile',
      'saving_label': 'Saving...',
      'save_profile_button': 'Save Profile',
      'category_basic': 'Basic',
      'category_personal': 'Personal',
      'category_goals': 'Goals',
      'category_work': 'Work',
      'category_lifestyle': 'Lifestyle',
      'category_interests': 'Interests',
      'category_personality': 'Personality',
      'category_media': 'Media',
      'category_location': 'Location',
      'category_prompts': 'Prompts',
      'category_verification': 'Verification',
      'username_label': 'User Name',
      'gender_label': 'Gender',
      'dob_label': 'Date of Birth',
      'interested_in_label': 'Interested In',
      'bio_about_label': 'Bio / About Me',
      'height_hint': 'e.g., 5\'10" or 178cm',
      'relationship_status_label': 'Relationship Status',
      'looking_for_label': 'Looking For',
      'open_to_long_distance_label': 'Open to long-distance?',
      'fitness_label': 'Fitness Level',
      'sleeping_habits_label': 'Sleeping Habits',
      'hobbies_label': 'Hobbies',
      'music_genres_label': 'Favorite Music Genres',
      'movies_shows_label': 'Favorite Movies/Shows',
      'weekend_activities_label': 'Weekend Activities',
      'political_views_label': 'Political Views',
      'add_photos_title': 'Add Your Photos',
      'upload_photos_sub': 'Upload at least 4 photos to stand out. Max 8.',
      'uploading_photos': 'Uploading photos...',
      'location_title': 'Your Location',
      'location_sub':
          'Sync your GPS to see potential matches nearby and calculate distances.',
      'city_neighborhood_label': 'City / Neighborhood',
      'location_synced': 'Location Synchronized',
      'location_not_set': 'Location Not Set',
      'update_location_button': 'Update Location',
      'sync_location_now_button': 'Sync Location Now',
      'prompts_title': 'Prompts',
      'perfect_date_prompt': 'A perfect date for me is...',
      'fall_for_you_prompt': 'I\'ll fall for you if...',
      'green_flag_prompt': 'My biggest green flag is...',
      'two_truths_prompt': 'Two truths and a lie...',
      'verification_title': 'Profile Verification',
      'verification_sub':
          'Get verified to show everyone that you\'re real! Verified profiles get 3x more matches.',
      'profile_verified': 'Profile Verified',
      'facial_verification': 'Facial Verification',
      'verification_confirmed_sub':
          'Your identity has been confirmed. You\'re all set!',
      'quick_scan_sub': 'A quick 3D face scan confirms you match your photos.',
      'start_verification_button': 'Start Verification',
      'profile_saved_snack': 'Profile saved successfully!',
      'failed_save_profile_snack': 'Failed to save profile',
      'location_services_disabled':
          'Location services are disabled. Please enable them.',
      'location_permission_denied': 'Location permissions are denied.',
      'location_permission_denied_forever':
          'Location permissions are permanently denied.',
      'fetching_coordinates': 'Fetching high-accuracy coordinates...',
      'location_updated_snack': 'Location updated and saved!',
      'error_fetching_location': 'Error fetching location',
      'select_date': 'Select Date',
      'active_now': 'Active now',
      'offline': 'Offline',
      'voice_call_tooltip': 'Voice Call',
      'video_call_tooltip': 'Video Call',
      'search_messages_hint': 'Search...',
      'no_messages_found': 'No messages found',
      'say_hi_to': 'Say hi to {name}!',
      'try_different_search': 'Try a different search term',
      'start_conversation': 'Start the conversation',
      'recording_label': 'Recording',
      'cancel_recording': 'Cancel',
      'chat_error_sending': 'Error sending message',
      'microphone_permission_denied': 'Microphone permission denied',
      'error_sending_voice': 'Error sending voice note',
      'error_uploading_image': 'Error uploading image',
      'clear_chat_title': 'Clear Chat',
      'clear_chat_confirm_message':
          'All messages with {name} will be permanently deleted. This cannot be undone.',
      'chat_cleared_snack': 'Chat cleared',
      'explore_header': 'Explore',
      'looking_for_header': 'What are you looking for?',
      'people_count_suffix': 'people',
      'cat_marriage': 'Marriage',
      'cat_marriage_sub': 'Lifelong commitment',
      'cat_long_term': 'Long Term',
      'cat_long_term_sub': 'Serious partner',
      'cat_hookups': 'Casual',
      'cat_hookups_sub': 'Casual & fun',
      'cat_short_term': 'Short Term Fun',
      'cat_short_term_sub': 'No strings attached',
      'cat_new_friends': 'New Friends',
      'cat_new_friends_sub': 'Platonic only',
      'cat_coffee_date': 'Coffee Date',
      'cat_coffee_date_sub': 'Relaxed vibes',
      'cat_movie_night': 'Movie Night',
      'cat_movie_night_sub': 'Film lovers',
      'cat_fitness_duo': 'Fitness Duo',
      'cat_fitness_duo_sub': 'Gym buddies',
      'cat_gaming_duo': 'Gaming Duo',
      'cat_gaming_duo_sub': 'Player 2?',
      'just_now': 'Just now',
      'min_ago': '{n} min ago',
      'hr_ago': '{n} hr ago',
      'yesterday': 'Yesterday',
      'days_ago': '{n} days ago',
      'today': 'Today',
      'earlier': 'Earlier',
      'call_cancelled': 'Call Cancelled',
      'incoming_video_call': 'INCOMING VIDEO CALL',
      'incoming_voice_call': 'INCOMING VOICE CALL',
      'decline': 'Decline',
      'accept': 'Accept',
      'call_ended': 'Call Ended',
      'dialing_video_call': 'Dialing Video Call...',
      'dialing_voice_call': 'Dialing Voice Call...',
      'mark_all_read': 'Mark all as read',
      'liked_profile_suffix': 'liked your profile',
      'missed_call_suffix': 'missed your call',
      'viewed_profile_suffix': 'viewed your profile',
      'no_notifications_title': 'Keep it quiet?',
      'no_notifications_sub': 'New likes and views will appear here',
      'rewind_confirm_title': 'Rewind Profile',
      'rewind_confirm_message':
          'Spend 100 sparks to rewind and see the last profile again?',
      'confirm_button': 'Confirm',
      'get_credits_button': 'Get Sparks',
      'insufficient_credits_title': 'Insufficient Sparks',
      'insufficient_credits_message':
          'You need at least 100 sparks to rewind. Would you like to get more now?',
      'unlock_for_credits': 'Unlock for 20 Sparks',
      'unlock_title': 'Unlock Profile',
      'unlock_message':
          'See who liked you for 20 sparks or upgrade to Premium for unlimited access.',
      'locked_profile': 'Locked Profile',
      'edit': 'Edit',
      'delete': 'Delete',
      'delete_message_title': 'Delete Message',
      'delete_message_confirm': 'Are you sure you want to delete this message?',
      'message_deleted': 'This message was deleted',
      'edited_badge': '(edited)',
      'edit_message': 'Edit Message',
      'insufficient_credits_msg':
          'You need 10 sparks to send a message. Upgrade to Premium for unlimited messaging!',
      'premium_benefit_msg': 'Premium members enjoy unlimited messaging!',
      'get_credits': 'Get Sparks',
      'cat_short_term_rel': 'Short Term Relationship',
      'cat_short_term_rel_sub': 'Something in between',
      'cat_sponsor': 'Travel the world',
      'cat_sponsor_sub': 'Let\'s explore together',
      'cat_figuring_out': 'Figuring Out',
      'cat_figuring_out_sub': 'Seeing where it goes',
      'nudge_send_more_likes': 'Send {count} more likes to get started',
      'chat_waiting_for_reply':
          'Waiting for {name} to accept your request. You can send more messages once they reply.',
      'chat_waiting_for_reply_hint': 'Waiting for reply...',
      'message_request_title': 'Message Request',
      'message_request_desc':
          'Do you want to let {name} message you? They won\'t know you\'ve seen their message until you accept.',
      'accept_request': 'Accept',
      'decline_request': 'Decline',
      'request_declined': 'Request declined. You cannot send messages.',
      'booking_section_title': 'Meetup Settings',
      'verification_status_unverified': 'Verify Identity',
      'verification_status_unverified_sub':
          'Submit ID for official verification',
      'verification_status_pending': 'Verification Pending',
      'verification_status_pending_sub': 'Your ID is being reviewed by admins',
      'verification_status_verified': 'Identity Verified',
      'verification_status_verified_sub':
          'Your identity has been fully confirmed',
      'national_id_number': 'National ID Number',
      'full_name_on_id': 'Full Name on ID',
      'id_document_photo': 'ID Document Photo',
      'submit_verification': 'Submit for Verification',
      'verification_submitted_success':
          'Verification details submitted successfully!',
      'use_mock_id': 'Use Mock ID Card',
      'simulated_admin_panel': 'Simulated Admin Action',
      'approve_request': 'Approve Request',
      'reject_request': 'Reject Request',
    },
    'sw': {
      'select_language': 'Chagua Lugha',
      'settings_title': 'Mipangilio',
      'account': 'Akaunti',
      'preferences': 'Mapendeleo',
      'discovery': 'Ugunduzi',
      'support': 'Msaada',
      'edit_profile': 'Hariri Wasifu',
      'edit_profile_sub': 'Badilisha maelezo ya wasifu wako',
      'email_settings': 'Mipangilio ya Barua Pepe',
      'email_settings_sub': 'Sasisha anwani yako ya barua pepe',
      'security': 'Usalama',
      'security_sub': 'Nenosiri, watumiaji waliozuiwa',
      'blocked_users': 'Watumiaji Waliozuiwa',
      'night_mode': 'Hali ya Usiku',
      'night_mode_on': 'Hali ya giza imewashwa',
      'night_mode_off': 'Hali ya mwanga imewashwa',
      'language': 'Lugha',
      'reset_swipes': 'Anza Upya Swipes',
      'reset_swipes_sub': 'Tazama wasifu uliopita tena',
      'help_center': 'Kituo cha Msaada',
      'help_center_sub': 'Maswali na msaada wa mazungumzo',
      'terms_of_service': 'Masharti ya Huduma',
      'terms_of_service_sub': 'Maelezo ya kisheria',
      'delete_account': 'Futa Akaunti',
      'delete_account_sub': 'Ondoa wasifu wako na data kabisa',
      'wipe_local_data': 'Futa Data ya Ndani',
      'wipe_local_data_sub': 'Futa cache na database ya ndani',
      'wipe_confirm_title': 'Futa Data ya Ndani?',
      'wipe_confirm_content':
          'Hii itafuta data zote zilizohifadhiwa ndani ikiwa ni pamoja na cache ya Firestore, mapendeleo yaliyoshirikiwa, na database ya ndani. Utahitaji kusawazisha tena na seva.\n\nKitendo hiki hakiwezi kubadilishwa.',
      'wipe_success': 'Data ya ndani imefutwa!',
      'wipe_failed': 'Imeshindwa kufuta data ya ndani.',
      'signin_title': 'Karibu Tena',
      'signin_sub': 'Ingia ili kuendelea na safari yako',
      'email': 'Anwani ya Barua Pepe',
      'password': 'Nenosiri',
      'forgot_password': 'Umesahau Nenosiri?',
      'signin_button': 'Ingia',
      'no_account': 'Huna akaunti?',
      'signup_link': 'Jisajili',
      'or_continue_with': 'Au endelea na',
      'google_signin': 'Endelea na Google',
      'like': 'Penda',
      'pass': 'Pita',
      'rewind': 'Rudisha',
      'view_profile': 'Tazama Wasifu',
      'no_profiles_title': 'Umeona kila mtu!',
      'no_profiles_sub': 'Rudi baadaye au fanya upya ili kuona wasifu tena.',
      'refresh_profiles': 'Fanya Upya Wasifu',
      'finding_matches': 'Tunatafuta wapenzi wako…',
      'like_stamp': 'PENDA',
      'nope_stamp': 'PITA',
      'add_photos_now': 'Ongeza Picha Sasa',
      'upload_more_photos_title': 'Pakia Picha Zaidi',
      'upload_more_photos_sub':
          'Ongeza angalau picha 4 kwenye wasifu wako ili kuendelea kupapasa, kuona wasifu, na kuvinjari picha.',
      'view_full_profile': 'Tazama Wasifu Kamili',
      'about_me': 'Kuhusu Mimi',
      'quick_facts': 'Ukweli wa Haraka',
      'background': 'Asili',
      'lifestyle': 'Mtindo wa Maisha',
      'relationship_goals': 'Malengo ya Mahusiano',
      'interests_hobbies': 'Mapendeleo na Burudani',
      'music_taste': 'Ladha ya Muziki',
      'personality': 'Tabia',
      'prompts': 'Vidokezo',
      'message': 'Ujumbe',
      'height_label': 'Urefu',
      'education_label': 'Elimu',
      'religion_label': 'Dini',
      'wants_kids_label': 'Anataka Watoto',
      'long_distance_label': 'Umbali Mrefu',
      'body_type_label': 'Aina ya Mwili',
      'status_label': 'Hali',
      'school_label': 'Shule',
      'want_kids_label': 'Unataka Watoto?',
      'occupation_label': 'Kazi',
      'industry_label': 'Sekta',
      'education_level_label': 'Kiwango cha Elimu',
      'introvert_extrovert_label': 'Mkimya au Mchangamfu?',
      'languages_spoken_label': 'Lugha',
      'smoking_label': 'Sigara',
      'drinking_label': 'Pombe',
      'exercise_label': 'Mazoezi',
      'diet_label': 'Chakula',
      'sleep_label': 'Usingizi',
      'pets_label': 'Wanyama wa Kufugwa',
      'zodiac_label': 'Alama ya Nyota',
      'personality_type_label': 'Aina ya Tabia',
      'social_style_label': 'Mtindo wa Jamii',
      'love_language_label': 'Lugha ya Mapenzi',
      'core_values_label': 'Maadili ya Msingi',
      'notifications': 'Arifa',
      'notifications_sub': 'Simamia arifa na sauti zako',
      'privacy_visibility': 'Faragha na Mwonekano',
      'show_age': 'Onyesha Umri',
      'show_age_sub': 'Onyesha umri wako kwenye wasifu wako',
      'show_distance': 'Onyesha Umbali',
      'show_distance_sub': 'Onyesha umbali wako kutoka kwa wengine.',
      'hide_profile': 'Ficha Wasifu',
      'hide_profile_sub': 'Ficha wasifu wako kwa muda kutoka kwa ugunduzi',
      'allow_messages_label': 'Ruhusu Ujumbe',
      'allow_messages_sub': 'Pokea ujumbe wa moja kwa moja kutoka kwa wengine.',
      'allow_bookings_label': 'Ruhusu Maombi ya Miadi',
      'allow_bookings_sub':
          'Ruhusu watumiaji wengine wakutumie maombi ya miadi.',
      'booking_preferences': 'Maelezo ya Miadi',
      'booking_details': 'Hariri Maelezo ya Miadi',
      'booking_details_sub': 'Weka eneo, bei, na sheria za miadi yako.',
      'booking_details_hint':
          'Maelezo haya yataonyeshwa kwa watumiaji wanaotaka kuweka miadi na wewe.',
      'booking_location_label': 'Eneo Unalopendelea',
      'booking_rate_label': 'Bei Yako / Mahitaji',
      'booking_notes_label': 'Sheria na Vidokezo',
      'my_bookings': 'Miadi Yangu',
      'reset_swipes_title': 'Anza Upya Swipes',
      'reset_swipes_content':
          'Hii itafuta historia ya wasifu uliowakataa. Utaona watumiaji uliowapita tena, lakini uliowapenda watabaki.\n\nHatua hii haiwezi kubadilishwa.',
      'cancel': 'Ghairi',
      'reset': 'Anza Upya',
      'swipes_reset_success': 'Swipes zimeanzishwa upya! Wasifu mpya unapakia.',
      'swipes_reset_failed':
          'Imeshindwa kuanzisha upya swipes. Tafadhali jaribu tena.',
      'photo_lock_snack': 'Pakia angalau picha 4 ili kuona picha zaidi!',
      'upload_label': 'Pakia',
      'messages_disabled_snack':
          'Mtumiaji huyu amezuia kutuma ujumbe wa moja kwa moja.',
      'refresh_cost_title': 'Thibitisha Upya',
      'refresh_cost_content':
          'Kufanya wasifu upya kunagharimu mikopo 50. Salio lako la sasa ni mikopo {credits}.',
      'not_enough_credits':
          'Huna mikopo ya kutosha. Tafadhali ongeza mikopo ili kufanya wasifu upya.',
      'pay_refresh': 'Lipa Mikopo 50',
      'send_gift': 'Tuma Zawadi',
      'gift_sent_success': 'Zawadi imetumwa!',
      'select_gift': 'Chagua Zawadi',
      'received_gift_suffix': 'amekutumia zawadi!',
      'signup_title': 'Jisajili',
      'signup_sub': 'Jiunge na Snellum na upate mwenza wako kamili',
      'signup_button': 'Jisajili',
      'full_name': 'Jina Kamili',
      'already_have_account': 'Tayari una akaunti?',
      'register_with': 'Au jisajili na',
      'fill_all_fields': 'Tafadhali jaza nafasi zote',
      'likes_label': 'Penda',
      'visitors_label': 'Wageni',
      'matches_label': 'Mechi',
      'account_section': 'Akaunti',
      'my_profile': 'Wasifu Wangu',
      'settings_label': 'Mipangilio',
      'discovery_section': 'Ugunduzi',
      'explore_people': 'Gundua Watu',
      'activity_section': 'Shughuli',
      'blog': 'Blogu',
      'live_videos': 'Video Chat',
      'finance_section': 'Fedha',
      'go_premium': 'Pata Premium',
      'my_credits': 'Kadi Zangu',
      'gifts': 'Zawadi',
      'transactions': 'Miamala',
      'appearance_section': 'Mwonekano',
      'support_section': 'Msaada',
      'about_us': 'Kuhusu Sisi',
      'safety_tips': 'Vidokezo vya Usalama',
      'logout': 'Ondoka',
      'logout_sub': 'Ondoka kwenye akaunti yako',
      'light_mode': 'Hali ya Mwanga',
      'dark_mode': 'Hali ya Giza',
      'nav_swipe': 'Papasa',
      'nav_explore': 'Gundua',
      'nav_likes': 'Penda',
      'nav_chat': 'Mazungumzo',
      'profile_needs_attention': 'Wasifu Unahitaji Makini',
      'profile_completion_sub':
          'Wasifu wako kwa sasa umekamilika kwa {completion}%. Unahitaji kukamilisha wasifu wako zaidi ya 40% kabla ya kuanza kulinganisha, kuzungumza, na kuvinjari!',
      'complete_profile_button': 'Kamilisha Wasifu',
      'signout_label': 'Ondoka',
      'unread_notifications': 'Arifa',
      'join_community': 'Jiunge na jumuiya',
      'signin_to_see_likes': 'Tafadhali ingia ili uone waliokupenda',
      'all_likes': 'Watu Wote Waliokupenda',
      'new_likes': 'Waliokupenda Hivi Karibuni',
      'no_likes_yet': 'Bado huna waliokupenda',
      'keep_swiping_matches': 'Endelea kupapasa ili upate wapenzi!',
      'someone_fallback': 'Mtu Fulani',
      'visitors_header': 'Wageni wa Hivi Karibuni',
      'no_visitors_yet': 'Bado huna wageni',
      'no_visitors_sub': 'Watu waliotembelea wasifu wako wataonekana hapa.',
      'messages_title': 'Ujumbe',
      'no_messages_yet': 'Bado huna ujumbe',
      'no_messages_sub': 'Mazungumzo yako yataonekana hapa.',
      'search_hint': 'Tafuta...',
      'signin_to_view_messages': 'Tafadhali ingia ili uone ujumbe wako',
      'failed_load_messages': 'Imeshindwa kupakia ujumbe',
      'retry_button': 'Jaribu Tena',
      'no_conversations_yet': 'Bado huna mazungumzo',
      'no_conversations_sub': 'Mpe mtu "like" ili kuanza mazungumzo',
      'new_matches_header': 'Mechi Mpya',
      'no_matches_yet_sub': 'Bado huna mechi. Endelea kupapasa!',
      'recent_messages_header': 'Ujumbe wa Hivi Karibuni',
      'say_hello': 'Sema habari!',
      'you_prefix': 'Wewe:',
      'user_fallback': 'Mtumiaji',
      'welcome_back': 'Karibu tena!',
      'profile_complete_title': 'Wasifu Umekamilika!',
      'complete_your_profile': 'Kamilisha Wasifu Wako',
      'tap_update_details': 'Gusa hapa ili kusasisha maelezo yako',
      'matches_3x_likely':
          'Uwezekano wa kupata mechi unaongezeka mara 3 ukiwa na wasifu kamili.',
      'views_label': 'Walioona',
      'edit_profile_label': 'Hariri Wasifu',
      'saving_label': 'Inahifadhi...',
      'save_profile_button': 'Hifadhi Wasifu',
      'category_basic': 'Msingi',
      'category_personal': 'Binafsi',
      'category_goals': 'Malengo',
      'category_work': 'Kazi',
      'category_lifestyle': 'Mtindo wa Maisha',
      'category_interests': 'Mapendeleo',
      'category_personality': 'Tabia',
      'category_media': 'Media',
      'category_location': 'Mahali',
      'category_prompts': 'Vidokezo',
      'category_verification': 'Uthibitisho',
      'username_label': 'Jina la Mtumiaji',
      'gender_label': 'Jinsia',
      'dob_label': 'Tarehe ya Kuzaliwa',
      'interested_in_label': 'Anayevutiwa Naye',
      'bio_about_label': 'Wasifu / Kuhusu Mimi',
      'height_hint': 'm.f., 5\'10" au 178sm',
      'relationship_status_label': 'Hali ya Uhusiano',
      'looking_for_label': 'Unachotafuta',
      'open_to_long_distance_label': 'Uko tayari kwa uhusiano wa mbali?',
      'fitness_label': 'Kiwango cha Mazoezi',
      'sleeping_habits_label': 'Tabia za Kulala',
      'hobbies_label': 'Mapendeleo',
      'music_genres_label': 'Ladha ya Muziki',
      'movies_shows_label': 'Sinema/Vipindi',
      'weekend_activities_label': 'Shughuli za Wikiendi',
      'political_views_label': 'Mitazamo ya Kisiasa',
      'add_photos_title': 'Ongeza Picha Zako',
      'upload_photos_sub':
          'Pakia angalau picha 4 ili upate nafasi zaidi. Max 8.',
      'uploading_photos': 'Inakia picha...',
      'location_title': 'Mahali Pako',
      'location_sub': 'Sawazisha GPS yako ili uone mechi karibu na wewe.',
      'city_neighborhood_label': 'Mji / Mtaa',
      'location_synced': 'Mahali Pamesawazishwa',
      'location_not_set': 'Mahali Haijawekwa',
      'update_location_button': 'Sasisha Mahali',
      'sync_location_now_button': 'Sawazisha Mahali Sasa',
      'prompts_title': 'Vidokezo',
      'perfect_date_prompt': 'Tarehe kamili kwangu ni...',
      'fall_for_you_prompt': 'Nitakupenda kama...',
      'green_flag_prompt': 'Sifa yangu bora ni...',
      'two_truths_prompt': 'Ukweli mbili na uongo mmoja...',
      'verification_title': 'Uthibitisho wa Wasifu',
      'verification_sub':
          'Thibitishwa ili kuonyesha kila mtu kuwa wewe ni wa kweli! Wasifu uliothibitishwa hupata mechi mara 3 zaidi.',
      'profile_verified': 'Wasifu Umethibitishwa',
      'facial_verification': 'Uthibitisho wa Uso',
      'verification_confirmed_sub':
          'Utambulisho wako umethibitishwa. Kila kitu kiko tayari!',
      'quick_scan_sub':
          'Scan ya haraka ya uso inathibitisha kuwa unalingana na picha zako.',
      'start_verification_button': 'Anza Uthibitisho',
      'profile_saved_snack': 'Wasifu umehifadhiwa kikamilifu!',
      'failed_save_profile_snack': 'Imeshindwa kuhifadhi wasifu',
      'location_services_disabled':
          'Huduma za eneo zimezimwa. Tafadhali ziwashe.',
      'location_permission_denied': 'Ruhusa za eneo zimekataliwa.',
      'location_permission_denied_forever':
          'Ruhusa za eneo zimekataliwa kabisa.',
      'fetching_coordinates': 'Inatafuta kuratibu...',
      'location_updated_snack': 'Mahali pamesasishwa na kuhifadhiwa!',
      'error_fetching_location': 'Hitilafu katika kutafuta eneo',
      'select_date': 'Chagua Tarehe',
      'active_now': 'Yuko mtandaoni',
      'offline': 'Hayuko mtandaoni',
      'voice_call_tooltip': 'Simu ya Sauti',
      'video_call_tooltip': 'Simu ya Video',
      'search_messages_hint': 'Tafuta ujumbe...',
      'no_messages_found': 'Hakuna ujumbe uliopatikana',
      'say_hi_to': 'Msalimie {name}!',
      'try_different_search': 'Jaribu neno lingine la utafutaji',
      'start_conversation': 'Anza mazungumzo',
      'recording_label': 'Inarekodi',
      'cancel_recording': 'Ghairi',
      'chat_error_sending': 'Hitilafu katika kutuma ujumbe',
      'microphone_permission_denied': 'Ruhusa ya maikrofoni imekataliwa',
      'error_sending_voice': 'Hitilafu katika kutuma sauti',
      'error_uploading_image': 'Hitilafu katika kupakia picha',
      'clear_chat_title': 'Futa Mazungumzo',
      'clear_chat_confirm_message':
          'Ujumbe wote na {name} utafutwa kabisa. Hii haiwezi kubadilishwa.',
      'chat_cleared_snack': 'Mazungumzo yamefutwa',
      'explore_header': 'Gundua',
      'looking_for_header': 'Unatafuta nini?',
      'people_count_suffix': 'watu',
      'cat_marriage': 'Ndoa',
      'cat_marriage_sub': 'Mwenza wa maisha',
      'cat_long_term': 'Uhusiano wa Muda Mrefu',
      'cat_long_term_sub': 'Mwenzi wa dhati',
      'cat_hookups': 'Uhusiano wa Kawaida',
      'cat_hookups_sub': 'Kufurahi tu',
      'cat_short_term': 'Muda Mfupi',
      'cat_short_term_sub': 'Bila masharti',
      'cat_new_friends': 'Marafiki Wapya',
      'cat_new_friends_sub': 'Marafiki tu',
      'cat_coffee_date': 'Tarehe ya Kahawa',
      'cat_coffee_date_sub': 'Hali ya utulivu',
      'cat_movie_night': 'Usiku wa Sinema',
      'cat_movie_night_sub': 'Wapenda filamu',
      'cat_fitness_duo': 'Wenzi wa Mazoezi',
      'cat_fitness_duo_sub': 'Marafiki wa gym',
      'cat_gaming_duo': 'Wenzi wa Michezo',
      'cat_gaming_duo_sub': 'Mchezaji wa pili?',
      'just_now': 'Sasa hivi',
      'min_ago': 'Dakika {n} zilizopita',
      'hr_ago': 'Saa {n} iliyopita',
      'yesterday': 'Jana',
      'days_ago': 'Siku {n} zilizopita',
      'today': 'Leo',
      'earlier': 'Mapema',
      'call_cancelled': 'Simu Imeghairiwa',
      'incoming_video_call': 'SIMU YA VIDEO INAINGIA',
      'incoming_voice_call': 'SIMU YA SAUTI INAINGIA',
      'decline': 'Kataa',
      'accept': 'Pokea',
      'call_ended': 'Simu Imekatika',
      'dialing_video_call': 'Inapiga Simu ya Video...',
      'dialing_voice_call': 'Inapiga Simu ya Sauti...',
      'mark_all_read': 'Weka zote kuwa zimesomwa',
      'liked_profile_suffix': 'amependa wasifu wako',
      'missed_call_suffix': 'amepiga simu hukuwa hewani',
      'viewed_profile_suffix': 'ameona wasifu wako',
      'no_notifications_title': 'Hakuna arifa kwanza?',
      'no_notifications_sub': 'Penda mpya na walioona wataonekana hapa',
      'rewind_confirm_title': 'Rudisha Wasifu',
      'rewind_confirm_message':
          'Tumia kadi 100 kurudisha na kuona wasifu wa mwisho tena?',
      'confirm_button': 'Thibitisha',
      'get_credits_button': 'Pata Kadi',
      'insufficient_credits_title': 'Kadi Hazitoshi',
      'insufficient_credits_message':
          'Unahitaji angalau kadi 100 ili kurudisha. Je, ungependa kupata zaidi sasa?',
      'unlock_for_credits': 'Fungua kwa Kadi 20',
      'unlock_title': 'Fungua Wasifu',
      'unlock_message':
          'Ona aliyekupenda kwa kadi 20 au pata Premium kwa ufikiaji usio na kikomo.',
      'locked_profile': 'Wasifu Umefungwa',
      'edit': 'Hariri',
      'delete': 'Futa',
      'delete_message_title': 'Futa Ujumbe',
      'delete_message_confirm': 'Je, una uhakika unataka kufuta ujumbe huu?',
      'message_deleted': 'Ujumbe huu ulifutwa',
      'edited_badge': '(ilihaririwa)',
      'edit_message': 'Hariri Ujumbe',
      'insufficient_credits_msg':
          'Unahitaji kadi 10 ili kutuma ujumbe. Pata Premium kwa ujumbe usio na kikomo!',
      'premium_benefit_msg':
          'Wanachama wa Premium hufurahia ujumbe usio na kikomo!',
      'get_credits': 'Pata Kadi',
      'cat_short_term_rel': 'Uhusiano wa Muda Mfupi',
      'cat_short_term_rel_sub': 'Kitu cha katikati',
      'cat_sponsor': 'Mdhamini',
      'cat_sponsor_sub': 'Maisha ya kifahari',
      'cat_figuring_out': 'Sijajua Bado',
      'nudge_send_more_likes': 'Tuma likes {count} zaidi ili kuanza',
      'chat_waiting_for_reply':
          'Unasubiri {name} akubali ombi lako. Unaweza kutuma ujumbe zaidi punde atakapokujibu.',
      'chat_waiting_for_reply_hint': 'Unasubiri jibu...',
      'message_request_title': 'Ombi la Ujumbe',
      'message_request_desc':
          'Je, ungependa kumruhusu {name} atume ujumbe? Hatatambua kuwa umeona ujumbe wake mpaka ukubali.',
      'accept_request': 'Kubali',
      'decline_request': 'Kataa',
      'request_declined': 'Ombi limekataliwa. Huwezi kutuma ujumbe.',
      'booking_section_title': 'Mipangilio ya Miadi',
      'verification_status_unverified': 'Thibitisha Utambulisho',
      'verification_status_unverified_sub':
          'Tuma Kitambulisho kwa uthibitisho rasmi',
      'verification_status_pending': 'Uthibitisho Unasubiriwa',
      'verification_status_pending_sub':
          'Kitambulisho chako kinakaguliwa na wasimamizi',
      'verification_status_verified': 'Utambulisho Umethibitishwa',
      'verification_status_verified_sub':
          'Utambulisho wako umethibitishwa kikamilifu',
      'national_id_number': 'Nambari ya Kitambulisho cha Taifa',
      'full_name_on_id': 'Jina Kamili Kwenye Kitambulisho',
      'id_document_photo': 'Picha ya Kitambulisho',
      'submit_verification': 'Tuma kwa Uthibitisho',
      'verification_submitted_success':
          'Maelezo ya uthibitisho yametunzwa kikamilifu!',
      'use_mock_id': 'Tumia Kitambulisho cha Jaribio',
      'simulated_admin_panel': 'Hatua ya Admin (Simulated)',
      'approve_request': 'Kubali Ombi',
      'reject_request': 'Kataa Ombi',
    },
  };
}
