// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdhrfzSwv_oS8vSiGwouglxRMOFg4PHzE',
    appId: '1:409694106333:web:39cc514cc46b7ffe202134',
    messagingSenderId: '409694106333',
    projectId: 'datedash-35789',
    authDomain: 'datedash-35789.firebaseapp.com',
    storageBucket: 'datedash-35789.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-yx4TvOokFDgjq46kkAee2AOKfQ81u8M',
    appId: '1:409694106333:android:e5c5d80ea3f99cce202134',
    messagingSenderId: '409694106333',
    projectId: 'datedash-35789',
    storageBucket: 'datedash-35789.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzIo5enXFJ1Uj1gH4-aNiX0g6FVv759GY',
    appId: '1:409694106333:ios:c5d3f6939efb796e202134',
    messagingSenderId: '409694106333',
    projectId: 'datedash-35789',
    storageBucket: 'datedash-35789.firebasestorage.app',
    iosClientId: '409694106333-rf9gc2dp1ovgejaolggaj5e262jaf4k5.apps.googleusercontent.com',
    iosBundleId: 'com.example.datedash',
  );
}
