# -*- coding: utf-8 -*-
"""Arabic translations dictionary mapping translation keys to high quality Modern Standard Arabic (MSA) text."""

AR_TRANSLATIONS = {
    # Chunk 0 (0-99)
    'select_language': 'اختر اللغة',
    'settings_title': 'الإعدادات',
    'account': 'الحساب',
    'my_meetups': 'لقاءاتي',
    'preferences': 'التفضيلات',
    'discovery': 'الاستكشاف',
    'video_chat': 'دردشة الفيديو',
    'support': 'الدعم',
    'edit_profile': 'تعديل الملف الشخصي',
    'edit_profile_sub': 'تعديل تفاصيل ملفك الشخصي',
    'email_settings': 'إعدادات البريد الإلكتروني',
    'email_settings_sub': 'تحديث عنوان بريدك الإلكتروني',
    'security': 'الأمان',
    'security_sub': 'كلمة المرور والمستخدمون المحظورون',
    'blocked_users': 'المستخدمون المحظورون',
    'night_mode': 'الوضع الليلي',
    'night_mode_on': 'تم تفعيل المظهر الداكن',
    'night_mode_off': 'تم تفعيل المظهر الفاتح',
    'language': 'اللغة',
    'reset_swipes': 'إعادة ضبط التمريرات',
    'reset_swipes_sub': 'مشاهدة الملفات الشخصية التي مررتها سابقاً مجدداً',
    'help_center': 'مركز المساعدة',
    'help_center_sub': 'الأسئلة الشائعة ودردشة الدعم',
    'terms_of_service': 'شروط الخدمة',
    'terms_of_service_sub': 'المعلومات القانونية',
    'delete_account': 'حذف الحساب',
    'delete_account_sub': 'إزالة ملفك الشخصي وبياناتك نهائياً',
    'wipe_local_data': 'مسح البيانات المحلية',
    'wipe_local_data_sub': 'مسح التخزين المؤقت وقاعدة البيانات المحلية',
    'wipe_confirm_title': 'مسح البيانات المحلية؟',
    'wipe_confirm_content': 'سيؤدي هذا إلى مسح جميع البيانات المخزنة محلياً بما في ذلك ذاكرة Firestore التخزينية والتفضيلات وقاعدة البيانات المحلية. ستحتاج إلى إعادة المزامنة مع الخادم.\\n\\nلا يمكن التراجع عن هذا الإجراء.',
    'wipe_success': 'تم مسح البيانات المحلية بنجاح!',
    'wipe_failed': 'فشل مسح البيانات المحلية.',
    'signin_title': 'مرحباً بعودتك',
    'signin_sub': 'سجل الدخول لمواصلة رحلتك',
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'forgot_password': 'هل نسيت كلمة المرور؟',
    'signin_button': 'تسجيل الدخول',
    'no_account': 'ليس لديك حساب؟',
    'signup_link': 'إنشاء حساب',
    'signup_button': 'إنشاء حساب',
    'or_continue_with': 'أو المتابعة باستخدام',
    'google_signin': 'المتابعة باستخدام Google',
    'like': 'إعجاب',
    'pass': 'تخطي',
    'rewind': 'تراجع',
    'view_profile': 'عرض الملف الشخصي',
    'no_profiles_title': 'لقد شاهدت الجميع!',
    'no_profiles_sub': 'عد لاحقاً أو حدّث الصفحة لإعادة استعراض الملفات الشخصية.',
    'refresh_profiles': 'تحديث الملفات الشخصية',
    'finding_matches': 'جارٍ البحث عن توافقاتك…',
    'like_stamp': 'إعجاب',
    'nope_stamp': 'تخطي',
    'add_photos_now': 'إضافة صور الآن',
    'upload_more_photos_title': 'تحميل المزيد من الصور',
    'upload_more_photos_sub': 'أضف ما لا يقل عن 4 صور إلى ملفك الشخصي لمواصلة التمرير وعرض الملفات الشخصية وتصفح الصور.',
    'view_full_profile': 'عرض الملف الشخصي كاملاً',
    'about_me': 'نبذة عني',
    'quick_facts': 'حقائق سريعة',
    'background': 'الخلفية',
    'lifestyle': 'أسلوب الحياة',
    'relationship_goals': 'أهداف العلاقة',
    'interests_hobbies': 'الاهتمامات والهوايات',
    'music_taste': 'الذوق الموسيقي',
    'personality': 'الشخصية',
    'prompts': 'أسئلة المحادثة',
    'message': 'رسالة',
    'height_label': 'الطول',
    'education_label': 'التعليم',
    'religion_label': 'الديانة',
    'wants_kids_label': 'يرغب في أطفال',
    'long_distance_label': 'علاقة عن بعد',
    'body_type_label': 'نوع الجسم',
    'status_label': 'الحالة',
    'school_label': 'المدرسة / الجامعة',
    'want_kids_label': 'هل تريد أطفالاً؟',
    'occupation_label': 'المهنة',
    'industry_label': 'مجال العمل',
    'education_level_label': 'المستوى التعليمي',
    'introvert_extrovert_label': 'انطوائي أم اجتماعي؟',
    'languages_spoken_label': 'اللغات',
    'smoking_label': 'التدخين',
    'drinking_label': 'شرب الكحول',
    'exercise_label': 'ممارسة الرياضة',
    'diet_label': 'النظام الغذائي',
    'sleep_label': 'عادات النوم',
    'pets_label': 'الحيوانات الأليفة',
    'zodiac_label': 'البرج',
    'personality_type_label': 'نوع الشخصية',
    'social_style_label': 'الأسلوب الاجتماعي',
    'love_language_label': 'لغة الحب',
    'core_values_label': 'القيم الأساسية',
    'notifications': 'الإشعارات',
    'notifications_sub': 'إدارة التنبيهات والأصوات',
    'privacy_visibility': 'الخصوصية والظهور',
    'show_age': 'إظهار العمر',
    'show_age_sub': 'عرض عمرك في ملفك الشخصي',
    'show_distance': 'إظهار المسافة',
    'show_distance_sub': 'عرض مدى بعدك عن الآخرين.',

    # Chunk 1 (100-199)
    'hide_profile': 'إخفاء الملف الشخصي',
    'hide_profile_sub': 'إخفاء ملفك الشخصي مؤقتاً من البحث والاستكشاف',
    'allow_messages_label': 'السماح بالرسائل',
    'allow_messages_sub': 'تلقي رسائل مباشرة من مستخدمين آخرين.',
    'allow_bookings_label': 'السماح بطلبات اللقاء',
    'allow_bookings_sub': 'السماح للمستخدمين الآخرين بإرسال طلبات لقاء إليك.',
    'booking_preferences': 'تفاصيل اللقاء',
    'booking_details': 'تعديل تفاصيل اللقاء',
    'booking_details_sub': 'حدد موقعك وقواعد اللقاءات الخاصة بك.',
    'booking_details_hint': 'ستظهر هذه التفاصيل للمستخدمين الذين يرغبون في مقابلتك.',
    'booking_location_label': 'الموقع المفضل',
    'booking_rate_label': 'الشروط والمتطلبات',
    'booking_notes_label': 'القواعد والملاحظات',
    'my_bookings': 'لقاءاتي',
    'reset_swipes_title': 'إعادة ضبط التمريرات',
    'reset_swipes_content': 'سيؤدي هذا إلى مسح سجل \"التخطي\". ستشاهد المستخدمين الذين تخطيتهم سابقاً مرة أخرى، مع الاحتفاظ بـ \"الإعجابات\".\\n\\nلا يمكن التراجع عن هذا الإجراء.',
    'cancel': 'إلغاء',
    'reset': 'إعادة ضبط',
    'swipes_reset_success': 'تمت إعادة ضبط التمريرات! جارٍ تحميل ملفات شخصية جديدة.',
    'swipes_reset_failed': 'فشلت إعادة ضبط التمريرات. يُرجى المحاولة مجدداً.',
    'photo_lock_snack': 'قم بتحميل 4 صور على الأقل لتصفح المزيد من الصور!',
    'upload_label': 'تحميل',
    'messages_disabled_snack': 'قام هذا المستخدم بتعطيل المراسلة المباشرة.',
    'refresh_cost_title': 'تأكيد التحديث',
    'refresh_cost_content': 'تكلفة تحديث الملفات الشخصية 50 شرارة. رصيدك الحالي {credits} شرارة.',
    'not_enough_credits': 'رصيد الشرارات غير كافٍ. يُرجى شحن الرصيد لتحديث الملفات الشخصية.',
    'pay_refresh': 'دفع 50 شرارة',
    'send_gift': 'إرسال هدية',
    'gift_sent_success': 'تم إرسال الهدية بنجاح!',
    'select_gift': 'اختر هدية',
    'received_gift_suffix': 'أرسل لك هدية!',
    'signup_title': 'إنشاء حساب',
    'signup_sub': 'انضم إلى Snellum واعثر على شريكك المثالي',
    'full_name': 'الاسم الكامل',
    'already_have_account': 'هل لديك حساب بالفعل؟',
    'register_with': 'أو التسجيل باستخدام',
    'fill_all_fields': 'يُرجى ملء جميع الحقول',
    'likes_label': 'الإعجابات',
    'visitors_label': 'الزوار',
    'matches_label': 'التوافقات',
    'account_section': 'الحساب',
    'my_profile': 'ملفي الشخصي',
    'settings_label': 'الإعدادات',
    'discovery_section': 'الاستكشاف',
    'explore_people': 'استكشاف الأشخاص',
    'activity_section': 'النشاط',
    'blog': 'المدونة',
    'live_videos': 'دردشة الفيديو',
    'finance_section': 'المالية',
    'go_premium': 'الترقية للمميز',
    'my_credits': 'شراراتي',
    'gifts': 'الهدايا',
    'transactions': 'المعاملات',
    'appearance_section': 'المظهر',
    'support_section': 'الدعم',
    'about_us': 'من نحن',
    'safety_tips': 'إرشادات الأمان',
    'logout': 'تسجيل الخروج',
    'logout_sub': 'تسجيل الخروج من حسابك',
    'light_mode': 'الوضع الفاتح',
    'dark_mode': 'الوضع الداكن',
    'nav_swipe': 'تصفح',
    'nav_explore': 'استكشاف',
    'nav_likes': 'الإعجابات',
    'nav_chat': 'الدردشة',
    'nav_video': 'فيديو',
    'profile_needs_attention': 'الملف الشخصي بحاجة إلى استكمال',
    'profile_completion_sub': 'ملفك الشخصي مكتمل حالياً بنسبة {completion}%. يجب إكمال أكثر من 40% لتتمكن من التوافق والدردشة والاستكشاف!',
    'complete_profile_button': 'إكمال الملف الشخصي',
    'signout_label': 'تسجيل الخروج',
    'unread_notifications': 'الإشعارات',
    'join_community': 'انضم إلى المجتمع',
    'signin_to_see_likes': 'يُرجى تسجيل الدخول لرؤية الإعجابات',
    'all_likes': 'جميع الإعجابات',
    'new_likes': 'إعجابات جديدة',
    'no_likes_yet': 'لا توجد إعجابات بعد',
    'keep_swiping_matches': 'استمر في التصفح للعثور على توافقات!',
    'someone_fallback': 'شخص ما',
    'visitors_header': 'الزوار الجدد',
    'no_visitors_yet': 'لا توجد مشاهدات بعد',
    'no_visitors_sub': 'سيظهر هنا الأشخاص الذين زاروا ملفك الشخصي.',
    'messages_title': 'الرسائل',
    'no_messages_yet': 'لا توجد رسائل بعد',
    'no_messages_sub': 'ستظهر محادثاتك هنا.',
    'search_hint': 'بحث...',
    'signin_to_view_messages': 'يُرجى تسجيل الدخول لعرض الرسائل',
    'failed_load_messages': 'فشل تحميل الرسائل',
    'retry_button': 'إعادة المحاولة',
    'no_conversations_yet': 'لا توجد محادثات بعد',
    'no_conversations_sub': 'أعجب بشخص لبدء محادثة معه',
    'new_matches_header': 'توافقات جديدة',
    'no_matches_yet_sub': 'لا توجد توافقات بعد. استمر في التصفح!',
    'recent_messages_header': 'الرسائل الأخيرة',
    'say_hello': 'قل مرحباً!',
    'you_prefix': 'أنت:',
    'user_fallback': 'مستخدم',
    'welcome_back': 'مرحباً بعودتك!',
    'profile_complete_title': 'الملف الشخصي مكتمل!',
    'complete_your_profile': 'أكمل ملفك الشخصي',
    'tap_update_details': 'انقر هنا لتحديث تفاصيلك',

    # Chunk 2 (200-299)
    'matches_3x_likely': 'تزيد فرص التوافق بمقدار 3 أضعاف مع ملف شخصي مكتمل.',
    'views_label': 'المشاهدات',
    'edit_profile_label': 'تعديل الملف الشخصي',
    'saving_label': 'جارٍ الحفظ...',
    'save_profile_button': 'حفظ الملف الشخصي',
    'category_basic': 'البيانات الأساسية',
    'category_personal': 'البيانات الشخصية',
    'category_goals': 'الأهداف',
    'category_work': 'العمل',
    'category_lifestyle': 'أسلوب الحياة',
    'category_interests': 'الاهتمامات',
    'category_personality': 'الشخصية',
    'category_media': 'الوسائط',
    'category_location': 'الموقع',
    'category_prompts': 'أسئلة المحادثة',
    'category_verification': 'التحقق',
    'username_label': 'اسم المستخدم',
    'gender_label': 'الجنس',
    'dob_label': 'تاريخ الميلاد',
    'interested_in_label': 'مهتم بـ',
    'bio_about_label': 'نبذة عني',
    'height_hint': 'مثال: 5\'10" أو 178 سم',
    'relationship_status_label': 'الحالة الاجتماعية',
    'looking_for_label': 'أبحث عن',
    'open_to_long_distance_label': 'هل تتقبل العلاقات عن بعد؟',
    'fitness_label': 'مستوى اللياقة البدنية',
    'sleeping_habits_label': 'عادات النوم',
    'hobbies_label': 'الهوايات',
    'music_genres_label': 'الأنواع الموسيقية المفضلة',
    'movies_shows_label': 'الأفلام والمسلسلات المفضلة',
    'weekend_activities_label': 'أنشطة عطلة نهاية الأسبوع',
    'political_views_label': 'التوجهات السياسية',
    'add_photos_title': 'أضف صورك',
    'upload_photos_sub': 'حمّل 4 صور على الأقل للتميز (بحد أقصى 8 صور).',
    'uploading_photos': 'جارٍ تحميل الصور...',
    'location_title': 'موقعك',
    'location_sub': 'مزامنة نظام تحديد المواقع (GPS) لرؤية التوافقات القريبة وحساب المسافات.',
    'city_neighborhood_label': 'المدينة / الحي',
    'location_synced': 'تمت مزامنة الموقع',
    'location_not_set': 'الموقع غير محدد',
    'update_location_button': 'تحديث الموقع',
    'sync_location_now_button': 'مزامنة الموقع الآن',
    'prompts_title': 'أسئلة المحادثة',
    'perfect_date_prompt': 'الموعد المثالي بالنسبة لي هو...',
    'fall_for_you_prompt': 'سأعجب بك فوراً إذا...',
    'green_flag_prompt': 'أكبر علامة إيجابية أبحث عنها هي...',
    'two_truths_prompt': 'حقيقتان وكذبة واحدة...',
    'verification_title': 'توثيق الملف الشخصي',
    'verification_sub': 'احصل على شارة التوثيق لتثبت للجميع أنك حقيقي! تحصل الحسابات الموثقة على 3 أضعاف التوافقات.',
    'profile_verified': 'ملف شخصي موثق',
    'facial_verification': 'التحقق من الوجه',
    'verification_confirmed_sub': 'تم تأكيد هويتك بنجاح. أنت جاهز تماماً!',
    'quick_scan_sub': 'فحص سريع ثلاثي الأبعاد للوجه للتأكد من مطابقتك لصورك.',
    'start_verification_button': 'بدء التحقق',
    'profile_saved_snack': 'تم حفظ الملف الشخصي بنجاح!',
    'failed_save_profile_snack': 'فشل حفظ الملف الشخصي',
    'location_services_disabled': 'خدمات الموقع معطلة. يُرجى تفعيلها.',
    'location_permission_denied': 'تم رفض إذن الوصول إلى الموقع.',
    'location_permission_denied_forever': 'تم رفض أذونات الموقع بشكل دائم.',
    'fetching_coordinates': 'جارٍ جلب إحداثيات الموقع بدقة عالية...',
    'location_updated_snack': 'تم تحديث الموقع وحفظه!',
    'error_fetching_location': 'خطأ في جلب الموقع',
    'select_date': 'تحديد التاريخ',
    'active_now': 'نشط الآن',
    'offline': 'غير متصل',
    'voice_call_tooltip': 'مكالمة صوتية',
    'video_call_tooltip': 'مكالمة فيديو',
    'search_messages_hint': 'بحث...',
    'no_messages_found': 'لم يتم العثور على رسائل',
    'say_hi_to': 'قل مرحباً لـ {name}!',
    'try_different_search': 'جرب كلمة بحث أخرى',
    'start_conversation': 'ابدأ المحادثة',
    'chat_emoji_tab': 'إيموجي',
    'chat_stickers_tab': 'ملصقات',
    'call_video_label': 'مكالمة فيديو',
    'call_voice_label': 'مكالمة صوتية',
    'call_cancel_label': 'إلغاء',
    'call_go_label': 'اتصال',
    'recording_label': 'جارٍ التسجيل',
    'cancel_recording': 'إلغاء',
    'chat_error_sending': 'خطأ أثناء إرسال الرسالة',
    'microphone_permission_denied': 'تم رفض إذن استخدام الميكروفون',
    'error_sending_voice': 'خطأ في إرسال التسجيل الصوتي',
    'error_uploading_image': 'خطأ في تحميل الصورة',
    'clear_chat_title': 'مسح المحادثة',
    'clear_chat_confirm_message': 'سيتم حذف جميع الرسائل مع {name} نهائياً. لا يمكن التراجع عن هذا الإجراء.',
    'chat_cleared_snack': 'تم مسح المحادثة',
    'explore_header': 'استكشاف',
    'looking_for_header': 'عما تبحث؟',
    'people_count_suffix': 'أشخاص',
    'cat_marriage': 'زواج',
    'cat_marriage_sub': 'التزام مدى الحياة',
    'cat_long_term': 'علاقة طويلة الأمد',
    'cat_long_term_sub': 'شريك جاد',
    'cat_hookups': 'علاقة غير رسمية',
    'cat_hookups_sub': 'عفوية ومرحة',
    'cat_short_term': 'علاقة قصيرة المدى',
    'cat_short_term_sub': 'بدون التزامات',
    'cat_new_friends': 'أصدقاء جدد',
    'cat_new_friends_sub': 'صداقة فقط',

    # Chunk 3 (300-399)
    'cat_coffee_date': 'موعد قهوة',
    'cat_coffee_date_sub': 'أجواء هادئة ومريحة',
    'cat_movie_night': 'التعرف على الثقافات',
    'cat_movie_night_sub': 'استكشاف العالم معاً',
    'cat_fitness_duo': 'شريك رياضي',
    'cat_fitness_duo_sub': 'رفيق للتمارين الرياضية',
    'cat_gaming_duo': 'شريك ألعاب',
    'cat_gaming_duo_sub': 'اللاعب الثاني؟',
    'just_now': 'الآن',
    'min_ago': 'منذ {n} دقيقة',
    'hr_ago': 'منذ {n} ساعة',
    'yesterday': 'أمس',
    'days_ago': 'منذ {n} أيام',
    'today': 'اليوم',
    'earlier': 'في وقت سابق',
    'call_cancelled': 'تم إلغاء المكالمة',
    'incoming_video_call': 'مكالمة فيديو واردة',
    'incoming_voice_call': 'مكالمة صوتية واردة',
    'decline': 'رفض',
    'accept': 'قبول',
    'call_ended': 'انتهت المكالمة',
    'dialing_video_call': 'جارٍ الاتصال بمكالمة فيديو...',
    'dialing_voice_call': 'جارٍ الاتصال بمكالمة صوتية...',
    'mark_all_read': 'تعيين الكل كمقروء',
    'liked_profile_suffix': 'أعجب بملفك الشخصي',
    'missed_call_suffix': 'مكالمة لم يرد عليها',
    'viewed_profile_suffix': 'شاهد ملفك الشخصي',
    'no_notifications_title': 'أجواء هادئة؟',
    'no_notifications_sub': 'ستظهر الإعجابات والمشاهدات الجديدة هنا',
    'rewind_confirm_title': 'تراجع عن التمرير',
    'rewind_confirm_message': 'إنفاق 100 شرارة للتراجع ومشاهدة آخر ملف شخصي مجدداً؟',
    'confirm_button': 'تأكيد',
    'get_credits_button': 'الحصول على شرارات',
    'insufficient_credits_title': 'رصيد شرارات غير كافٍ',
    'insufficient_credits_message': 'تحتاج إلى 100 شرارة على الأقل للتراجع. هل ترغب في الحصول على المزيد الآن؟',
    'unlock_for_credits': 'فتح مقابل 20 شرارة',
    'unlock_title': 'فتح الملف الشخصي',
    'unlock_message': 'اكتشف من أبدى إعجابه بك مقابل 20 شرارة أو قم بالترقية إلى المميز للوصول غير المحدود.',
    'locked_profile': 'ملف شخصي مقفل',
    'edit': 'تعديل',
    'delete': 'حذف',
    'delete_chat': 'حذف المحادثة',
    'delete_chat_title': 'حذف المحادثة',
    'delete_chat_confirm': 'هل أنت متأكد من رغبتك في حذف المحادثة مع {name}؟ سيؤدي هذا إلى إزالتها من قائمة رسائلك.',
    'chat_deleted_snack': 'تم حذف المحادثة',
    'delete_message_title': 'حذف الرسالة',
    'delete_message_confirm': 'هل أنت متأكد من رغبتك في حذف هذه الرسالة؟',
    'message_deleted': 'تم حذف هذه الرسالة',
    'edited_badge': '(معدلة)',
    'edit_message': 'تعديل الرسالة',
    'insufficient_credits_msg': 'تحتاج إلى 10 شرارات لإرسال رسالة. قم بالترقية إلى المميز لمراسلة غير محدودة!',
    'premium_benefit_msg': 'يتمتع الأعضاء المميزون بمراسلة غير محدودة!',
    'get_credits': 'الحصول على شرارات',
    'cat_short_term_rel': 'علاقة قصيرة المدى',
    'cat_short_term_rel_sub': 'شيء بين الصداقة والارتباط',
    'cat_sponsor': 'السفر حول العالم',
    'cat_sponsor_sub': 'دعنا نستكشف معاً',
    'cat_figuring_out': 'استكشاف الأمور',
    'cat_figuring_out_sub': 'لنرى إلى أين ستسير الأمور',
    'nudge_send_more_likes': 'أرسل {count} إعجابات إضافية للبدء',
    'chat_waiting_for_reply': 'في انتظار قبول {name} لطلبك. يمكنك إرسال المزيد من الرسائل بمجرد الرد.',
    'chat_waiting_for_reply_hint': 'في انتظار الرد...',
    'message_request_title': 'طلب مراسلة',
    'message_request_desc': 'هل تريد السماح لـ {name} بمراسلتك؟ لن يعلم بأنك شاهدت الرسالة حتى تقبل الطلب.',
    'accept_request': 'قبول',
    'decline_request': 'رفض',
    'request_declined': 'تم رفض الطلب. لا يمكنك إرسال رسائل.',
    'booking_section_title': 'إعدادات اللقاء',
    'verification_status_unverified': 'تأكيد الهوية',
    'verification_status_unverified_sub': 'التحقق من خلال فحص الهوية من Stripe',
    'verification_status_pending': 'التحقق قيد المراجعة',
    'verification_status_pending_sub': 'يجري فحص هويتك بواسطة Stripe',
    'verification_status_failed': 'فشل التحقق',
    'verification_status_failed_sub': 'تم إلغاء التحقق أو رفضه. انقر للمحاولة مجدداً.',
    'verification_status_verified': 'تم التحقق من الهوية',
    'verification_status_verified_sub': 'تم تأكيد هويتك بالكامل بنجاح',
    'national_id_number': 'رقم الهوية الوطنية',
    'full_name_on_id': 'الاسم الكامل كما في الهوية',
    'id_document_photo': 'صورة وثيقة الهوية',
    'submit_verification': 'إرسال للتحقق',
    'verification_submitted_success': 'بدأت عملية التحقق بنجاح!',
    'use_mock_id': 'استخدام بطاقة هوية تجريبية',
    'simulated_admin_panel': 'إجراء إداري تجريبي',
    'approve_request': 'الموافقة على الطلب',
    'reject_request': 'رفض الطلب',
    'continue_with_phone': 'المتابعة باستخدام الهاتف',
    'verify_phone_code': 'التحقق من رمز الهاتف',
    'enter_phone_prompt': 'أدخل رقم هاتفك المسجل لتلقي\\nرمز التحقق.',
    'enter_code_sent_to': 'أدخل الرمز المكون من 6 أرقام المرسل إلى\\n{phone}',
    'send_code': 'إرسال الرمز',
    'verify_and_continue': 'التحقق والمتابعة',
    'change_phone_number': 'تغيير رقم الهاتف',
    'resend_code_sms': 'إعادة إرسال الرمز عبر SMS',
    'resend_available_in': 'إعادة الإرسال متاحة خلال {sec} ثانية',
    'rewards': 'المكافآت',
    'boost_profile': 'تعزيز الملف الشخصي',
    'manage_subscription': 'إدارة الاشتراك',
    'manage_or_upgrade_plan': 'إدارة الخطة أو الترقية',
    'upgrade_to_premium': 'الترقية للمميز',
    'active_status': 'نشط',

    # Chunk 4 (400-499)
    'expired_status': 'منتهي الصلاحية',
    'standard_status': 'أساسي',
    'cancel_membership': 'إلغاء العضوية',
    'cancel_membership_confirm': 'هل أنت متأكد من رغبتك في إلغاء عضويتك؟',
    'activate_now': 'تفعيل الآن',
    'expires_at': 'ينتهي في',
    'purchased_on': 'تم الشراء في',
    'nav_premium': 'مميز',
    'boost_profile_sub': 'احصل على ظهور أكبر بمقدار 10 أضعاف',
    'active_plan_manage': 'الخطة النشطة • إدارة أو ترقية',
    'my_memberships': 'عضوياتي',
    'tap_activate_switch': 'انقر على تفعيل للتبديل',
    'activate': 'تفعيل',
    'keep_plan': 'الاحتفاظ بالخطة',
    'yes_cancel': 'نعم، قم بالإلغاء',
    'subscription_plan': 'الاشتراك والخطة',
    'updating_membership': 'جارٍ تحديث العضوية...',
    'active_challenges': 'التحديات النشطة',
    'invite_earn': 'ادعُ واربح',
    'invite_earn_sub': 'اربح 500 شرارة عن كل صديق ينضم ويؤكد بريده الإلكتروني — بلا حدود!',
    'sparks_label': 'شرارات',
    'claimed_label': 'تم التحصيل',
    'invited_label': 'تمت دعوتهم',
    'invite_friends': 'دعوة الأصدقاء',
    'invite_friends_sub': 'بلا حدود — اربح شرارات عن كل صديق يتم التحقق منه',
    'your_invite_link': 'رابط الدعوة الخاص بك',
    'copy_link': 'نسخ الرابط',
    'share_link': 'مشاركة الرابط',
    'people_you_invited': 'الأشخاص الذين دعوتهم',
    'link_copied': 'تم نسخ الرابط!',
    'no_one_yet': 'لا يوجد أحد بعد — شارك رابطك!',
    'every_friend_earns': 'كل صديق يؤكد بريده الإلكتروني يمنحك 500 شرارة',
    'email_verified': 'تم التحقق من البريد',
    'email_not_verified': 'لم يتم التحقق من البريد بعد',
    'already_claimed_badge': '✓ تم التحصيل',
    'pending_badge': 'قيد الانتظار',
    'free_tier_label': 'الخطة المجانية',
    'free_account': 'حساب مجاني',
    'queued_memberships': 'العضويات في قائمة الانتظار',
    'queued_preserved_sub': 'هذه العضويات محفوظة وسيتم تفعيلها تلقائياً، أو يمكنك التبديل إليها الآن.',
    'switch_label': 'تبديل',
    'preserved_in_queue': 'محفوظة في قائمة الانتظار',
    'days_remaining': 'أيام متبقية',
    'your_plan_privileges': 'ميزات خطتك',
    'current_tier_privileges': 'ميزات المستوى الحالي',
    'change_or_upgrade': 'تغيير أو ترقية المستوى',
    'monthly_subscription': 'اشتراك شهري',
    'weekly_subscription': 'اشتراك أسبوعي',
    'standard_free_access': 'مستوى الوصول المجاني الأساسي',
    'membership_cancelled_success': 'تم إلغاء عضويتك بنجاح.',
    'go_premium_sub': 'قم بالترقية لفتح جميع ميزات وتدعيمات VIP',
    'monthly_membership': 'عضوية شهرية',
    'weekly_membership': 'عضوية أسبوعية',
    'rewards_header': 'المكافآت',
    'sparks_count_label': 'شرارات',
    'complete_challenges': 'أكمل التحديات واجمع المكافآت',
    'boost_profile_active': '⚡ نشط حتى {date}',
    'settings': 'الإعدادات',
    'get_premium': 'الحصول على المميز',
    'no_active_period': 'لا توجد فترة نشطة',
    'days_remaining_label': 'متبقي {n} أيام',
    'hours_minutes_remaining': 'متبقي {h} س و {m} د',
    'minutes_remaining': 'متبقي {m} دقيقة',
    'expiring_soon': 'ينتهي قريباً',
    'expiring_less_than_minute': 'ينتهي خلال أقل من دقيقة',
    'percent_left': 'متبقي {n}%',
    'activated_on': 'تم التفعيل في',
    'expires_renews': 'ينتهي / يتجدد في',
    'access_level': 'مستوى الوصول',
    'full_vip_access': 'وصول كامل لميزات VIP',
    'standard_tier': 'المستوى الأساسي',
    'active_badge': 'نشط',
    'expired_badge': 'منتهي',
    'standard_badge': 'أساسي',
    'done_badge': 'مكتمل',
    'ready_badge': 'جاهز',
    'open_badge': 'متاح',
    'claim_reward': 'تحصيل المكافأة',
    'in_progress': 'قيد التقدم',
    'claimed': 'تم التحصيل',
    'limit_reached': 'تم بلوغ الحد الأقصى',
    'free_usage': 'استخدام مجاني',
    'sparks_claimed_success': 'تم تحصيل {amount} شرارة بنجاح!',
    'already_claimed': 'تم تحصيل المكافأة لهذا المستخدم مسبقاً',
    'sparks_claimed_snack': 'تمت إضافة +500 شرارة!',
    'share_link_snack': 'تم نسخ الرابط! شاركه مع الأصدقاء.',
    'manage_subscription_screen_title': 'الاشتراك والخطة',
    'yes_label': 'نعم، إلغاء',
    'keep_plan_label': 'الاحتفاظ بالخطة',
    'cancel_confirm_body': 'هل أنت متأكد من رغبتك في إلغاء عضويتك؟ ستفقد فوراً جميع ميزات الحساب المميز وتعود إلى المستوى المجاني الأساسي.',
    'remove_from_queue': 'إزالة من قائمة الانتظار',
    'are_you_sure_remove': 'هل أنت متأكد من رغبتك في إزالة هذا الاشتراك من قائمة الانتظار؟ لا يمكن التراجع عن هذا الإجراء.',
    'keep_label': 'احتفاظ',
    'remove_label': 'إزالة',
    'queued_removed': 'تمت إزالة الاشتراك من قائمة الانتظار',
    'activate_membership_title': 'تفعيل عضوية {plan}',
    'activate_membership_body': 'سيؤدي هذا إلى جعل {plan} خطتك النشطة. سيتم حفظ خطتك الحالية {current} بأمان في قائمة الانتظار مع الاحتفاظ بالمدة المتبقية.',
    'switch_to_plan': 'التبديل إلى {plan}؟',
    'switch_to_plan_body': 'سيتم تفعيل {plan} على الفور. وسيتم وضع خطتك الحالية في قائمة الانتظار مع الحفاظ على الأيام المتبقية.',
    'membership_activated': 'عضوية {plan} نشطة الآن!',

    # Chunk 5 (500-599)
    'membership_activated_snack': 'تم تفعيل عضوية {plan}!',
    'get_sparks_button': 'الحصول على شرارات',
    'month_label': 'شهر واحد',
    'days_label': '{n} أيام',
    'go_premium_sub_small': 'قم بالترقية لفتح جميع ميزات VIP',
    'subscription_title': 'الاشتراك والخطة',
    'discovery_filters': 'مرشحات الاستكشاف',
    'basic_demographics': 'البيانات الديموغرافية الأساسية',
    'show_me': 'أظهر لي',
    'looking_for': 'أبحث عن',
    'age_range': 'الفئة العمرية',
    'strict_age_match': 'تطابق عمري دقيق',
    'strict_age_sub': 'سنعرض ملفات شخصية أبعد قليلاً إذا نفدت الخيارات.',
    'maximum_distance': 'المسافة القصوى',
    'strict_distance_match': 'تطابق مسافة دقيق',
    'strict_distance_sub': 'سنقترح أشخاصاً أبعد إذا نفدت الخيارات.',
    'premium_advanced_filters': 'مرشحات مميزة متقدمة',
    'relationship_status': 'الحالة الاجتماعية',
    'religion_beliefs': 'الديانة / المعتقدات',
    'smoking_habits': 'عادات التدخين',
    'drinking_habits': 'عادات شرب الكحول',
    'zodiac_sign': 'البرج الفلكي',
    'education_level': 'المستوى التعليمي',
    'online_now_only': 'المتصلون بالإنترنت فقط',
    'online_now_sub': 'إظهار المستخدمين النشطين حالياً فقط.',
    'kids_children': 'الأطفال',
    'pets': 'الحيوانات الأليفة',
    'personality_type': 'نوع الشخصية',
    'max_photos_needed': 'الحد الأقصى للصور المطلوبة',
    'photos_count': '{n} صور',
    'any_count': 'أي عدد',
    'must_have_bio': 'يشترط وجود نبذة تعريفية',
    'must_have_bio_sub': 'إظهار المستخدمين الذين كتبوا نبذة شخصية فقط.',
    'family_plans': 'الخطط العائلية',
    'communication_style': 'أسلوب التواصل',
    'love_style': 'أسلوب الحب',
    'elite_advanced_filters': 'مرشحات Elite المتقدمة',
    'verified_profiles_only': 'الملفات الموثقة فقط',
    'verified_profiles_sub': 'إظهار المستخدمين الذين تحققوا من هويتهم فقط.',
    'partner_country': 'بلد الشريك (البطاقة الخضراء)',
    'apply_filters': 'تطبيق المرشحات',
    'feature_exclusive': 'ميزة {tier}',
    'feature_exclusive_desc': 'المرشحات المتقدمة حصرية لأعضاء {tier}. قم بترقية خطتك للحصول على وصول غير محدود وفتح مرشحات {tier}!',
    'maybe_later': 'ربما لاحقاً',
    'upgrade': 'ترقية',
    'error_saving_filters': 'خطأ في حفظ المرشحات: {e}',
    'tap_to_unlock': 'انقر للفتح',
    'verify_first_love': 'تحقق من الحب الحقيقي أولاً',
    'dont_act_be_you': 'كن على طبيعتك لمدة 60 ثانية دون تصنع.',
    'match_preferences': 'تفضيلات التوافق',
    'match_preferences_sub': 'تُستخدم هذه التفضيلات قبل بدء البحث عبر الكاميرا في كامل الشاشة.',
    'partner_language': 'لغة الشريك',
    'premium_elite_filters': 'مرشحات Premium و Elite',
    'desired_gender': 'الجنس المطلوب',
    'chatting_now': 'يتحدثون الآن',
    'filters_on': 'المرشحات مفعّلة',
    'filters_limited': 'مرشحات محدودة',
    'start_matching': 'بدء التوافق',
    'cancel_search': 'إلغاء البحث',
    'finding_your_match': 'جارٍ البحث عن شريكك المتوافق...',
    'search_language_hint': 'بحث عن لغة...',
    'search_country_hint': 'بحث عن دولة...',
    'select_partner_language': 'اختر لغة الشريك',
    'select_partner_country': 'اختر دولة الشريك',
    'reply': 'رد',
    'image_unavailable': 'الصورة غير متوفرة',
    'you_sent_gift': 'أرسلت {gift}!',
    'sent_you_gift': 'أرسل لك {gift}!',
    'credits_amount': '{n} رصيد',
    'replying_to_yourself': 'الرد على نفسك',
    'replying_to_user': 'الرد على {user}',
    'its_a_match': 'إنه توافق!',
    'you_and_liked_each_other': 'أعجبت أنت و{name} ببعضكما البعض.',
    'send_a_message': 'إرسال رسالة',
    'keep_swiping': 'مواصلة التصفح',
    'keep_swiping_title': 'مواصلة التصفح',
    'you_missed_a_match': 'لقد فاتك توافق!',
    'missed_match_desc': 'لقد قمت للتو بتخطي شخص كان قد أعجب بملفك الشخصي. كان مهتماً بك!',
    'rewind_match': 'استعادة التوافق',
    'unlock_rewind': 'فتح ميزة التراجع',
    'send_gift_title': 'إرسال هدية',
    'gift_not_enough_credits': 'رصيد غير كافٍ!',
    'setup_profile': 'إعداد الملف الشخصي',
    'step_n_of_total': 'الخطوة {step} من {total}',
    'score_n': 'النسبة: {n}%',
    'the_basics': 'الأساسيات',
    'the_basics_sub': 'قدم نفسك للمجتمع',
    'enter_first_name': 'أدخل اسمك الأول',
    'identity_title': 'الهوية',
    'identity_sub': 'من أنت وما الذي يناسب شخصيتك؟',
    'goals_status_title': 'الأهداف والحالة',
    'goals_status_sub': 'ما الذي تبحث عنه في Snellum؟',
    'habits_lifestyle_title': 'العادات وأسلوب الحياة',
    'habits_lifestyle_sub': 'ساعد التوافقات في فهم عاداتك اليومية',
    'personality_vibe_title': 'الشخصية والأجواء',
    'personality_vibe_sub': 'ما الذي يجعلك متميزاً؟',
    'tell_us_more_title': 'أخبرنا المزيد',
    'tell_us_more_sub': 'أين تعيش وما هي قصتك؟',
    'photos_title': 'الصور',
    'photos_sub': 'أظهر أفضل زواياك!',

    # Chunk 6 (600-699)
    'upload_photos': 'تحميل الصور',
    'upload_photos_wizard_desc': 'حمّل ما يصل إلى 6 صور عالية الجودة. إضافة الصور تزيد من اكتمال ملفك بشكل كبير.',
    'uploading_photos_progress': 'جارٍ تحميل الصور المختارة...',
    'profile_completion_alert': 'ملفك الشخصي مكتمل حالياً بنسبة {n}%. أضف المزيد من التفاصيل أو الصور لتصل إلى 40%!',
    'select_your_country': 'اختر بلدك',
    'your_country_location': 'موقعك / بلدك',
    'select_country_hint': 'اختر بلدك',
    'bio_hint': 'أخبرنا قليلاً عن نفسك...',
    'max_6_photos_wizard': 'يمكنك تحميل 6 صور كحد أقصى في هذا الدليل.',
    'or_type_own': 'أو اكتب خيارك الخاص',
    'reward_history': 'سجل المكافآت',
    'total_sparks_received': 'إجمالي الشرارات المستلمة',
    'no_rewards_yet': 'لا توجد مكافآت بعد',
    'no_rewards_sub': 'تلقّ الهدايا من المستخدمين الآخرين أو أكمل النشاط اليومي لكسب المكافآت!',
    'daily_activity_reward': 'مكافأة النشاط اليومي',
    'gift_received': 'تم استلام هدية',
    'sparks_count': '+{n} شرارة',
    'you_received_a_gift': 'لقد استلمت هدية!',
    'received_tab': 'الواردة',
    'sent_tab': 'المرسلة',
    'no_sent_requests': 'لا توجد طلبات مرسلة بعد.',
    'no_received_requests': 'لا توجد طلبات واردة بعد.',
    'to_user': 'إلى: {name}',
    'from_user': 'من: {name}',
    'date_time_label': 'التاريخ والوقت',
    'location_label': 'الموقع',
    'rate_req_label': 'التقييم / الشروط',
    'message_label': 'رسالة',
    'chat_btn': 'دردشة',
    'accept_btn': 'قبول',
    'decline_btn': 'رفض',
    'cancel_request_btn': 'إلغاء الطلب',
    'meetup_status_updated': 'تم تحديث حالة اللقاء إلى {status}!',
    'error_updating_status': 'خطأ في تحديث الحالة: {e}',
    'notif_master_control': 'التحكم الرئيسي',
    'notif_alert_preferences': 'تفضيلات التنبيه',
    'notif_types_section': 'أنواع الإشعارات',
    'notif_allow': 'السماح بالإشعارات',
    'notif_allow_sub': 'تفعيل أو تعطيل جميع الإشعارات',
    'notif_sound': 'صوت الإشعار',
    'notif_sound_sub': 'تشغيل صوت للتنبيهات الواردة',
    'notif_vibrate': 'الاهتزاز',
    'notif_vibrate_sub': 'الاهتزاز عند تلقي الإشعارات',
    'notif_matches': 'توافقات جديدة',
    'notif_matches_sub': 'تلقي إشعار عند حصولك على توافق جديد',
    'notif_messages': 'الرسائل',
    'notif_messages_sub': 'تلقي إشعار عند وصول رسائل دردشة جديدة',
    'notif_likes': 'الإعجابات',
    'notif_likes_sub': 'تلقي إشعار عندما يُعجب شخص بملفك الشخصي',
    'notif_calls': 'المكالمات',
    'notif_calls_sub': 'تلقي إشعارات للمكالمات الصوتية والمرئية',
    'app_lock_section': 'أمان قفل التطبيق',
    'social_boundaries_section': 'الحدود الاجتماعية',
    'update_credentials_section': 'تحديث بيانات الأمان',
    'lock_app_pin': 'قفل التطبيق برمز PIN',
    'lock_app_pin_sub': 'طلب رمز PIN مكون من 4 أرقام عند فتح التطبيق',
    'change_access_pin': 'تغيير رمز PIN للدخول',
    'lock_app_biometrics': 'قفل التطبيق بالبصمة الحيوية',
    'lock_app_biometrics_sub': 'استخدام بصمة الإصبع أو التعرف على الوجه',
    'blocked_users_manage_sub': 'إدارة حدودك والملفات الشخصية المحظورة',
    'blocked_count': '{n} محظور',
    'total_count': '{n} إجمالي',
    'change_password': 'تغيير كلمة المرور',
    'change_password_sub': 'تأكد من استخدام كلمة مرور قوية لحماية حسابك من الوصول غير المصرح به.',
    'current_password': 'كلمة المرور الحالية',
    'new_password': 'كلمة المرور الجديدة',
    'confirm_new_password': 'تأكيد كلمة المرور الجديدة',
    'show_label': 'إظهار',
    'hide_label': 'إخفاء',
    'update_password': 'تحديث كلمة المرور',
    'send_reset_email': 'إرسال رابط إعادة تعيين كلمة المرور',
    'pin_setup_title_create': 'إنشاء رمز PIN من 4 أرقام',
    'pin_setup_title_confirm': 'تأكيد رمز PIN المكون من 4 أرقام',
    'pin_setup_sub': 'سيؤمن هذا الرمز وصولك إلى تطبيق Snellum.',
    'enter_current_pin': 'أدخل رمز PIN الحالي للتطبيق',
    'verify_identity_action': 'يُرجى تأكيد هويتك لتنفيذ هذا الإجراء.',
    'pin_setup_success': 'تم إعداد رمز PIN لقفل التطبيق بنجاح!',
    'pin_mismatch': 'رمزا PIN غير متطابقين. يُرجى المحاولة مرة أخرى.',
    'pin_disabled_success': 'تم تعطيل قفل PIN بنجاح.',
    'pin_incorrect': 'رمز PIN غير صحيح. يُرجى المحاولة مرة أخرى.',
    'biometric_enabled': 'تم تفعيل التحقق الحيوي.',
    'biometric_disabled': 'تم تعطيل التحقق الحيوي.',
    'biometric_set_pin_first': 'يُرجى تعيين رمز PIN أولاً قبل تفعيل البصمة الحيوية.',
    'biometric_not_supported': 'الأجهزة الحيوية غير مدعومة أو غير مهيأة على هذا الجهاز.',
    'biometric_no_enrolled': 'لا توجد بصمات أصابع أو بصمة وجه مسجلة على هذا الجهاز.',
    'biometric_auth_failed': 'فشلت المصادقة الحيوية. تعذر تفعيل القفل الحيوي.',
    'biometric_error_prefix': 'خطأ في المصادقة الحيوية: ',
    'unblocked_success': 'تم إلغاء حظر {name} بنجاح.',
    'unblock_label': 'إلغاء الحظر',
    'clean_slate': 'صفحة جديدة!',
    'no_blocked_users_sub': 'لا يوجد مستخدمون محظورون. تصفح بأمان واستمتاع.',
    'blocked_users_cannot_message': 'لا يمكن للمستخدمين في هذه القائمة التمرير عليك أو مراسلتك أو عرض بطاقة ملفك الشخصي.',
    'validate_current_password': 'يُرجى إدخال كلمة المرور الحالية',
    'validate_new_password': 'يُرجى إدخال كلمة المرور الجديدة',
    'validate_password_min': 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل',
    'validate_confirm_password': 'يُرجى تأكيد كلمة المرور الجديدة',
    'validate_passwords_match': 'كلمتا المرور غير متطابقتين',
    'password_updated_success': 'تم تحديث كلمة المرور بنجاح!',
    'password_reset_email_sent': 'تم إرسال رابط إعادة تعيين كلمة المرور إلى {email}.',
    'no_email_found': 'لم يتم العثور على عنوان بريد إلكتروني مسجل.',

    # Chunk 7 (700-799)
    'no_transactions_yet': 'لا توجد معاملات بعد',
    'payment_history_here': 'سيظهر سجل مدفوعاتك هنا',
    'error_loading_transactions': 'خطأ في تحميل المعاملات',
    'payment_confirmed': 'تم تأكيد الدفع! تم تحديث حسابك بنجاح.',
    'reverify_payment_tooltip': 'إعادة التحقق من الدفع',
    'verification_error_prefix': 'خطأ في التحقق: ',
    'error_no_tracking_id': 'خطأ: لم يتم العثور على معرف تتبع لهذه المعاملة',
    'challenge_daily_explorer_title': 'مستكشف يومي',
    'challenge_daily_explorer_desc': 'استخدم Snellum لمدة 3 ساعات اليوم',
    'challenge_profile_pro_title': 'ملف شخصي محترف',
    'challenge_profile_pro_desc': 'أكمل 100% من ملفك الشخصي',
    'challenge_trusted_member_title': 'عضو موثوق',
    'challenge_trusted_member_desc': 'قم بتوثيق حسابك',
    'challenge_welcome_bonus_title': 'هدية الترحيب',
    'challenge_welcome_bonus_desc': 'انضم إلى مجتمع Snellum',
    'challenge_completed_label': 'مكتمل',
    'not_logged_in': 'لم يتم تسجيل الدخول',
    'error_loading_meetups': 'خطأ في تحميل اللقاءات: {error}',
    'call_ended_by_partner_finding_match': 'أنهى الشريك المكالمة. جارٍ البحث عن توافق جديد...',
    'insufficient_sparks_message_unlimited': 'رصيد الشرارات غير كافٍ! تحتاج إلى 10 شرارات لكل رسالة أو اشترك في العضوية لمراسلة غير محدودة.',
    'report_user_title': 'الإبلاغ عن مستخدم',
    'report_partner_guidelines': 'الإبلاغ عن {name} لانتهاك الإرشادات:',
    'submit_report': 'إرسال البلاغ',
    'report_submitted_skipping_next': 'تم إرسال البلاغ. الانتقال إلى المستخدم التالي...',
    'block_user_title': 'حظر المستخدم',
    'block_user_confirmation': 'هل أنت متأكد من رغبتك في حظر {partnerName}؟ سيتم قطع الاتصال ولن تتوافقا مرة أخرى.',
    'blocked_partner_skipping_next': 'تم حظر {partnerName}. الانتقال إلى المستخدم التالي...',
    'one_on_one_chat_with': 'محادثة فردية مع {partnerName}',
    'chat_unlocks_in_seconds': '🔒 يفتح خلال {seconds} ثانية...',
    'chat_locked_by_you': '🔒 المحادثة مقفلة بواسطتك',
    'chat_locked_by_partner': '🔒 المحادثة مقفلة بواسطة {partnerName}',
    'messages_save_to_inbox': '🔓 يتم حفظ الرسائل مباشرة في صندوق الوارد',
    'unlock_chat': 'فتح المحادثة',
    'lock_chat': 'قفل المحادثة',
    'chat_unlocks_after_two_minutes': 'تفتح المحادثة بعد دقيقتين (120 ثانية) من المكالمة',
    'you_have_locked_chat': 'لقد قمت بقفل المحادثة',
    'partner_has_locked_chat': 'قام {partnerName} بقفل المحادثة',
    'say_hi_to_partner': 'قل مرحباً لـ {partnerName}!',
    'sender_sent_gift': 'أرسل {senderName} {giftName}!',
    'sender_colon_message': '{senderName}: {message}',
    'chat_unlocks_in_seconds_hint': 'تفتح المحادثة خلال {seconds} ثانية...',
    'chat_locked_by_you_hint': 'المحادثة مقفلة بواسطتك (انقر على رمز القفل للفتح)',
    'chat_locked_by_partner_hint': 'المحادثة مقفلة بواسطة {partnerName}',
    'type_message_saves_to_inbox': 'اكتب رسالة (تُحفظ في صندوق الوارد)...',
    'report': 'إبلاغ',
    'block': 'حظر',
    'end_call': 'إنهاء المكالمة',
    'next': 'التالي',
    'failed_to_delete': 'فشل الحذف: {error}',
    'super': 'ممتاز',
    'failed_to_unlock': 'فشل إلغاء القفل: {error}',
    'best_value': 'أفضل قيمة',
    'could_not_open_chat': 'تعذر فتح المحادثة: {error}',
    'your_balance_sparks': 'رصيدك: {credits} شرارة',
    'email_verified_snack': 'تم التحقق من البريد الإلكتروني بنجاح. مرحباً بك في Snellum.',
    'error_generic': 'حدث خطأ ما',
    'not_logged_in_screen': 'لم يتم تسجيل الدخول',
    'no_account_found_phone': 'لم يتم العثور على حساب مرتبط برقم الهاتف هذا. يُرجى التحقق من الرقم أو التسجيل.',
    'valid_phone_required': 'يُرجى إدخال رقم هاتف صالح',
    'code_sent_check_inbox': 'تم إرسال رمز التحقق إلى {email}. تفقد صندوق الوارد.',
    'send_code_failed_with_error': 'تعذر إرسال رمز التحقق: {error}',
    'error_with_details': 'خطأ: {error}',
    'verification_code_sent_to_phone': 'تم إرسال رمز التحقق إلى {phone}',
    'invalid_verification_code': 'رمز التحقق غير صالح. يُرجى التحقق والمحاولة مجدداً.',
    'phone_number': 'رقم الهاتف',
    'phone_number_hint': 'رقم الهاتف',
    'search_country': 'بحث عن دولة',
    'enter_full_6_digit_code': 'يُرجى إدخال الرمز المكون من 6 أرقام كاملاً',
    'email_verified_welcome': 'تم التحقق من البريد الإلكتروني بنجاح. مرحباً بك في Snellum.',
    'authentication_failed': 'فشلت المصادقة.',
    'verification_error_with_details': 'خطأ في التحقق: {error}',
    'verify_email_title': 'تأكيد بريدك الإلكتروني',
    'we_sent_code_to': 'أرسلنا رمز تحقق مكوناً من 6 أرقام إلى',
    'check_spam_junk_folder': 'إذا لم تجد البريد الإلكتروني، تفقد مجلد البريد العشوائي (Spam).',
    'didnt_get_code_resend': 'لم يصلك الرمز؟ إعادة إرسال الرمز',
    'not_logged_in_meetups': 'لم يتم تسجيل الدخول',
    'failed_cancel_membership': 'فشل إلغاء العضوية: {error}',
    'switch_plan_title': 'التبديل إلى {newPlanName}؟',
    'switch_plan_desc': 'سيؤدي هذا إلى تفعيل {newPlanName} على الفور. وسيتم وضع خطتك الحالية في قائمة الانتظار مع الاحتفاظ بالأيام المتبقية.',
    'error_activating_plan': 'خطأ في تفعيل الخطة: {error}',
    'remove_queue_title': 'إزالة {planName} من قائمة الانتظار؟',
    'remove_queue_desc': 'هل أنت متأكد من رغبتك في إزالة هذه العضوية من قائمة الانتظار؟ لا يمكن التراجع عن هذا الإجراء.',
    'keep': 'احتفاظ',
    'error_remove_queued': 'خطأ في إزالة الاشتراك من قائمة الانتظار: {error}',
    'hours_mins_remaining': 'متبقي {hours} س و {mins} د',
    'expiring_minute': 'ينتهي خلال أقل من دقيقة',
    'free_tier': 'الخطة المجانية',
    'plan_pass_status': 'تصريح {planName}',
    'status_active': 'نشط',
    'status_expired': 'منتهي الصلاحية',
    'status_standard': 'أساسي',
    'standard_free_tier': 'مستوى الوصول المجاني الأساسي',
    'unknown': 'غير معروف',
    'never': 'أبداً',
    'plan_privileges': 'ميزات خطتك',
    'queued_memberships_count': 'العضويات في قائمة الانتظار ({count})',
    'queued_memberships_desc': 'هذه العضويات محفوظة وسيتم تفعيلها تلقائياً، أو يمكنك التبديل إليها الآن.',
    'plan_pass_status_premium': 'مميز',
    'cancel_plan_title': 'إلغاء عضوية {planName}؟',
    'cancel_plan_desc': 'هل أنت متأكد من رغبتك في إلغاء عضويتك؟ ستفقد فوراً جميع الميزات المميزة وتعود إلى المستوى المجاني الأساسي.',

    # Chunk 8 (800-899)
    'loss_unlimited_likes': 'إعجابات وتمريرات تراجع غير محدودة',
    'loss_video_voice': 'ميزات مكالمات الفيديو والصوت عالية الدقة',
    'loss_priority_visibility': 'أولوية التوافق VIP وظهور مميز للملف الشخصي',
    'error_generic_error': 'خطأ: {error}',
    'payment_pending_failed': 'لا تزال عملية الدفع معلقة أو فشلت على الخادم.',
    'verification_error': 'خطأ في التحقق: {error}',
    'no_transactions': 'لا توجد معاملات بعد',
    'sparks_amount': '{sparkAmount} شرارة',
    'reverify_payment': 'إعادة التحقق من الدفع',
    'plan_pro': 'احترافي',
    'plan_premium': 'مميز',
    'plan_elite': 'نخبة',
    'subscriptions_tab': 'الاشتراكات',
    'sparks_tab': 'الشرارات',
    'billing_weekly': 'أسبوعياً',
    'billing_monthly': 'شهرياً',
    'plan_benefits_title': 'مزايا {title}',
    'back_to_plans': 'العودة إلى الخطط',
    'most_popular': 'الأكثر شعبية',
    'elite_sparks_bonus': '+2,000 شرارة',
    'view_all_benefits': 'عرض جميع المزايا ({count})',
    'choose_plan': 'اختيار الخطة',
    'available_balance': 'الرصيد المتاح',
    'sparks': 'شرارات',
    'purchase_sparks': 'شراء شرارات',
    'bonus_10000_free': '10,000 مجاناً',
    'best_value_badge': 'أفضل قيمة',
    'confirm_details': 'تأكيد التفاصيل',
    'operator_payment': 'الدفع عبر {operatorName}',
    'amount_to_pay': 'المبلغ المطلوب دفعه',
    'phone_hint_airtel': '09xxxxxxx',
    'phone_hint_tnm': '08xxxxxxx',
    'enter_valid_number': 'يُرجى إدخال رقم صحيح',
    'confirm_and_pay': 'تأكيد والدفع',
    'change_payment_method': 'تغيير طريقة الدفع',
    'securely_processing': 'جارٍ المعالجة بأمان...',
    'processing_prompt_desc': 'قم بتأكيد طلب الدفع على جهازك. قد يستغرق هذا بضع ثوانٍ.',
    'payment_successful': 'تم الدفع بنجاح!',
    'success_elite': 'رائع! تم تفعيل اشتراكك في باقة النخبة وإضافة 2,000 شرارة إلى رصيدك!',
    'success_subscription': 'رائع! اشتراكك في باقة {plan} نشط وجاهز للاستخدام الآن.',
    'success_sparks_added': 'رائع! تمت إضافة {sparks} شرارة إلى رصيدك!',
    'sparks_added_badge': '+{sparks} شرارة تمت إضافتها',
    'done': 'تم!',
    'payment_failed': 'فشلت عملية الدفع',
    'try_again': 'إعادة المحاولة',
    'payment_failed_short': 'فشل الدفع',
    'payment_timeout': 'انتهت المهلة: يستغرق التحقق من الدفع وقتاً طويلاً. يُرجى التحقق من رصيدك أو التواصل مع الدعم.',
    'select_payment_method': 'اختر طريقة الدفع',
    'choose_operator': 'اختر شركة الدفع عبر الهاتف المحمول المفضلة لديك',
    'failed_load_operators': 'فشل تحميل خيارات الدفع.',
    'operator_country_currency': '{countryName} • {currency}',
    'amount_mwk': '{price} كواشا ملاوية',
    'mobile_number': 'رقم الهاتف المحمول',
    'crop_image': 'قص الصورة',
    'failed_process_image': 'فشلت معالجة الصورة: {error}',
    'add_caption_hint': 'إضافة تعليق...',
    'live_stream_default_title': 'بث مباشر',
    'gift_sent_chat_message': 'أرسل {giftType}!',
    'live_you_label': 'أنت',
    'live_host_label': 'المضيف',
    'live_guest_label': 'الضيف',
    'live_host_tag': '{hostName} (المضيف)',
    'live_cohost_tag': '{guestName} (مضيف مشارك)',
    'live_camera_off_message': 'كاميرا {name} مغلقة',
    'live_fallback_name': 'مباشر',
    'live_badge_label': 'مباشر',
    'live_end_button': 'إنهاء',
    'live_leave_button': 'مغادرة',
    'live_unmute_label': 'إلغاء الكتم',
    'live_mute_label': 'كتم الصوت',
    'live_show_camera_label': 'إظهار الكاميرا',
    'live_hide_camera_label': 'إخفاء الكاميرا',
    'live_leave_seat_label': 'مغادرة المقعد',
    'live_remove_guest_label': 'إزالة الضيف',
    'live_invite_match_label': 'دعوة توافق',
    'live_invite_a_match_title': 'دعوة شخص متوافق',
    'live_no_matches_found': 'لم يتم العثور على توافقات. تصفح للحصول على توافقات أولاً!',
    'invitation_sent_snack': 'تم إرسال الدعوة إلى {match.firstName}!',
    'invite_button': 'دعوة',
    'say_something_hint': 'قل شيئاً…',
    'gender_option_male': 'ذكر',
    'gender_option_female': 'أنثى',
    'gender_option_non_binary': 'غير ثنائي',
    'gender_option_other': 'آخر',
    'interested_in_men': 'رجال',
    'interested_in_women': 'نساء',
    'interested_in_everyone': 'الجميع',
    'relationship_single': 'أعزب / عزباء',
    'relationship_married': 'متزوج / متزوجة',
    'relationship_divorced': 'مطلق / مطلقة',
    'relationship_widowed': 'أرمل / أرملة',
    'relationship_separated': 'منفصل / منفصلة',
    'looking_for_marriage': 'زواج',
    'looking_for_long_term': 'علاقة طويلة الأمد',
    'looking_for_short_term': 'علاقة قصيرة المدى',
    'looking_for_casual': 'علاقة غير رسمية',
    'looking_for_short_term_fun': 'تسلية ومرح قصير المدى',
    'looking_for_coffee_date': 'موعد قهوة',
    'looking_for_new_friends': 'أصدقاء جدد',
    'looking_for_learn_cultures': 'التعرف على ثقافات جديدة',

    # Chunk 9 (900-982)
    'looking_for_travel_world': 'السفر حول العالم',
    'looking_for_figuring_out': 'استكشاف الخيارات',
    'smoking_yes': 'نعم',
    'smoking_no': 'لا',
    'smoking_occasionally': 'أحياناً',
    'drinking_yes': 'نعم',
    'drinking_no': 'لا',
    'drinking_socially': 'في المناسبات',
    'want_kids_yes': 'نعم',
    'want_kids_no': 'لا',
    'want_kids_maybe': 'ربما',
    'want_kids_already_have': 'لدي أطفال بالفعل',
    'occupation_student': 'طالب / طالبة',
    'occupation_entrepreneur': 'رائد أعمال',
    'occupation_teacher': 'معلم / معلمة',
    'occupation_nurse': 'ممرض / ممرضة',
    'occupation_engineer': 'مهندس / مهندسة',
    'occupation_designer': 'مصمم / مصممة',
    'occupation_developer': 'مطور برمجيات',
    'occupation_manager': 'مدير / مديرة',
    'family_plans_label': 'الخطط العائلية',
    'communication_style_label': 'أسلوب التواصل',
    'love_style_label': 'أسلوب التعبير عن الحب',
    'music_genres_hint': 'بوب، روك، آر أند بي...',
    'core_values_hint': 'العائلة، الطموح، الصدق...',
    'lat_long_display': 'خط العرض: {lat}، خط الطول: {long}',
    'required_badge': 'مطلوب',
    'max_8_photos_snack': 'يمكنك إضافة ما يصل إلى 8 صور فقط.',
    'upload_starting_snack': 'جارٍ بدء تحميل {n} صور...',
    'upload_server_error': 'خطأ في الخادم: {message}',
    'upload_http_error': 'خطأ HTTP: {code}',
    'upload_connection_error': 'خطأ في الاتصال: {e}',
    'upload_all_saved_snack': 'تم تحميل جميع الصور وحفظها بنجاح!',
    'upload_partial_snack': 'تم تحميل {n} من أصل {m} صور وحفظ الملف الشخصي.',
    'upload_failed_snack': 'فشل التحميل. تفقد سجلات الخادم.',
    'tap_to_enter_hint': 'انقر للإدخال...',
    'add_custom_options_hint': 'أضف خيارات مخصصة مفصولة بفواصل',
    'ask_me_option': 'اسألني',
    'claim_pro': 'تحصيل {title}',
    'claim_reward_button': 'تحصيل الآن',
    'status_badge_done': 'مكتمل',
    'status_badge_ready': 'جاهز',
    'status_badge_open': 'متاح',
    'challenge_daily_hours_progress': '{hours} س / 3 س',
    'challenge_welcome_gift_title': 'هدية الترحيب',
    'challenge_welcome_gift_desc': 'انضم إلى مجتمع Snellum',
    'completed': 'مكتمل',
    'invite_earn_title': 'ادعُ واربح',
    'invite_earn_title_claim': 'تحصيل الشرارات',
    'send_gift_title_fallback': 'إرسال هدية',
    'error_generic_gift': 'خطأ: {error}',
    'progress_percent': '{percent}%',
    'activate_plan_title': 'تفعيل عضوية {newPlanName}',
    'activate_plan_desc': 'سيؤدي هذا إلى جعل {newPlanName} عضويتك النشطة. سيتم وضع خطتك الحالية {currentPlanName} بأمان في قائمة الانتظار مع الاحتفاظ بالوقت المتبقي.',
    'failed_switch_membership': 'فشل تبديل العضوية: {error}',
    'premium_member_badge': 'عضو {premiumType}',
    'plan_days_remaining': 'متبقي {days} أيام',
    'plan_hours_remaining': 'متبقي {hours} ساعات',
    'plan_mins_remaining': 'متبقي {mins} دقائق',
    'send_gift_button': 'إرسال الهدية',
    'gift_cost_label': 'التكلفة: {cost} شرارة',
    'gift_error': 'خطأ في إرسال الهدية: {error}',
    'confirm_delete_message_title': 'حذف الرسالة',
    'confirm_delete_message_content': 'هل أنت متأكد من رغبتك في حذف هذه الرسالة؟',
    'edit_message_label': 'تعديل الرسالة',
    'cancel_delete': 'إلغاء',
    'confirm_delete': 'حذف',
    'cancel_gift': 'إلغاء',
    'request_message_title': 'طلب مراسلة',
    'request_message_desc': 'يريد {senderName} بدء محادثة معك',
    'report_submitted_snack': 'تم إرسال البلاغ. شكراً لمساعدتك في الحفاظ على أمان {appName}.',
    'not_enough_credits_to_unlock': 'رصيد الشرارات غير كافٍ. يُرجى الشحن لفتح المحتوى.',
    'verify_otp_failed': 'رمز التحقق غير صالح. يُرجى التحقق والمحاولة مجدداً.',
    'session_expired_reroute': 'انتهت صلاحية الجلسة. يُرجى إعادة إدخال رقمك.',
    'login_failed_with_error': 'فشل تسجيل الدخول: {error}',
    'send_otp_failed': 'تعذر إرسال رمز التحقق: {error}',
    'invalid_otp': 'رمز التحقق غير صالح. يُرجى التحقق والمحاولة مجدداً.',
    'continue_with_phone_title': 'المتابعة باستخدام الهاتف',
    'send_code_button': 'إرسال الرمز',
    'verify_continue_button': 'التحقق والمتابعة',
    'resend_code_in': 'إعادة إرسال الرمز خلال {seconds} ثانية',
    'phone_auth_title': 'المصادقة عبر الهاتف',
    'otp_hint': '000000',
}
